catalog_toyota_token:
  path:         /toyota/catalog/0/{token}/{regionCode}
  defaults:     {_controller: CatalogToyotaBundle:Catalog:regionsModels, token: null, regionCode: null}

catalog_toyota:
  path:         /toyota/{regionCode}
  defaults:     {_controller: CatalogToyotaBundle:Catalog:regionsModels, regionCode: null}

catalog_toyota_modifications:
  path:         /toyota/catalog/1
  defaults:     {_controller: CatalogToyotaBundle:Catalog:modifications}
  requirements: {_method: POST}

catalog_toyota_complectations:
  path:         /toyota/catalog/2/{regionCode}/{modelCode}/{modificationCode}/{token}
  defaults:     {_controller: CatalogToyotaBundle:Catalog:complectations, token: null}

catalog_toyota_complectation_korobka:
  path:         /toyota/catalog/12
  defaults:     {_controller: CatalogToyotaBundle:Catalog:complectation_korobka}
  requirements: {_method: POST}

catalog_toyota_groups:
  path:         /toyota/catalog/3/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{token}
  defaults:     {_controller: CatalogToyotaBundle:Catalog:groups, token: null}

catalog_toyota_subgroups:
  path:         /toyota/catalog/4/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{token}
  defaults:     {_controller: CatalogToyotaBundle:Catalog:subgroups, token: null}

catalog_toyota_schemas:
  path:         /toyota/catalog/5/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{token}
  defaults:     {_controller: CatalogToyotaBundle:Catalog:schemas, token: null}

catalog_toyota_schema:
  path:         /toyota/catalog/6/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{schemaCode}/{token}
  defaults:     {_controller: CatalogToyotaBundle:Catalog:schema, token: null}

catalog_toyota_articuls:
  path:         /toyota/catalog/7
  defaults:     {_controller: CatalogToyotaBundle:Catalog:articuls}
  requirements: {_method: POST}

catalog_toyota_group:
  path:         /toyota/catalog/8/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{subGroupCode}/{token}
  defaults:     {_controller: CatalogToyotaBundle:Catalog:getGroupBySubgroup, token: null}

#------------------------------------------------------------------------------

vin_toyota:
  path:         /toyota/vin/0/{token}
  defaults:     {_controller: CatalogToyotaBundle:Vin:index, token: null}

vin_toyota_result:
  path:         /toyota/vin/1
  defaults:     {_controller: CatalogToyotaBundle:Vin:result}
  requirements: {_method: POST}

vin_toyota_groups:
  path:         /toyota/vin/3/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{token}
  defaults:     {_controller: CatalogToyotaBundle:Vin:groups, token: null}

vin_toyota_subgroups:
  path:         /toyota/vin/4/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{token}
  defaults:     {_controller: CatalogToyotaBundle:Vin:subgroups, token: null}

vin_toyota_schemas:
  path:         /toyota/vin/5/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{token}
  defaults:     {_controller: CatalogToyotaBundle:Vin:schemas, token: null}

vin_toyota_schema:
  path:         /toyota/vin/6/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{schemaCode}/{token}
  defaults:     {_controller: CatalogToyotaBundle:Vin:schema, token: null}

vin_toyota_articuls:
  path:         /toyota/vin/7
  defaults:     {_controller: CatalogToyotaBundle:Vin:articuls}
  requirements: {_method: POST}

vin_toyota_group:
  path:         /toyota/vin/8/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{subGroupCode}/{token}
  defaults:     {_controller: CatalogToyotaBundle:Vin:vinGroupBySubgroup, token: null}

#---------------------------------------------------------------------------------------------

articul_toyota:
  path:         /toyota/articul/0/{token}
  defaults:     {_controller: CatalogToyotaBundle:Articul:index, token: null}

articul_toyota_find_token:
  path:         /toyota/articul/1/{token}/{regionCode}
  defaults:     {_controller: CatalogToyotaBundle:Articul:findByArticul, token: null, regionCode: null}

articul_toyota_find:
  path:         /toyota/articul/2/{regionCode}
  defaults:     {_controller: CatalogToyotaBundle:Articul:findByArticul, regionCode: null}

articul_toyota_modifications:
  path:         /toyota/articul/3
  defaults:     {_controller: CatalogToyotaBundle:Articul:modifications}
  requirements: {_method: POST}

articul_toyota_complectations:
  path:         /toyota/articul/4/{regionCode}/{modelCode}/{modificationCode}/{articul}/{token}
  defaults:     {_controller: CatalogToyotaBundle:Articul:toyotaArticulComplectations, token: null}

articul_toyota_groups:
  path:         /toyota/articul/5/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{articul}/{token}
  defaults:     {_controller: CatalogToyotaBundle:Articul:toyotaArticulgroups, token: null}

articul_toyota_subgroups:
  path:         /toyota/articul/6/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{articul}/{token}
  defaults:     {_controller: CatalogToyotaBundle:Articul:toyotaArticulSubgroups, token: null}

articul_toyota_schemas:
  path:         /toyota/articul/7/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{articul}/{token}
  defaults:     {_controller: CatalogToyotaBundle:Articul:toyotaArticulSchemas, token: null}

articul_toyota_schema:
  path:         /toyota/articul/8/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{schemaCode}/{articul}/{token}
  defaults:     {_controller: CatalogToyotaBundle:Articul:toyotaArticulSchema, token: null}

articul_toyota_articuls:
  path:         /toyota/articul/9
  defaults:     {_controller: CatalogToyotaBundle:Articul:articuls}
  requirements: {_method: POST}

articul_toyota_group:
  path:         /toyota/articul/8/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{subGroupCode}/{token}
  defaults:     {_controller: CatalogToyotaBundle:Articul:getGroupBySubgroup, token: null}
catalog_toyota_homepage:
    path:     /hello/{name}
    defaults: { _controller: CatalogToyotaBundle:Default:index }
