catalog_gmc_token:
  path:         /gmc/catalog/0/{token}/{regionCode}
  defaults:     {_controller: CatalogGmcBundle:Catalog:regionsModels, token: null, regionCode: null}

catalog_gmc:
  path:         /gmc/{regionCode}
  defaults:     {_controller: CatalogGmcBundle:Catalog:regionsModels, regionCode: null}

catalog_gmc_modifications:
  path:         /gmc/catalog/1
  defaults:     {_controller: CatalogGmcBundle:Catalog:modifications}
  requirements: {_method: POST}

catalog_gmc_complectations:
  path:         /gmc/catalog/2/{regionCode}/{modelCode}/{modificationCode}/{token}
  defaults:     {_controller: CatalogGmcBundle:Catalog:complectations, token: null}

catalog_gmc_groups:
  path:         /gmc/catalog/3/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{token}
  defaults:     {_controller: CatalogGmcBundle:Catalog:groups, token: null}

catalog_gmc_subgroups:
  path:         /gmc/catalog/4/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{token}
  defaults:     {_controller: CatalogGmcBundle:Catalog:subgroups, token: null}

catalog_gmc_schemas:
  path:         /gmc/catalog/5/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{token}
  defaults:     {_controller: CatalogGmcBundle:Catalog:schemas, token: null}

catalog_gmc_schema:
  path:         /gmc/catalog/6/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{schemaCode}/{token}
  defaults:     {_controller: CatalogGmcBundle:Catalog:schema, token: null}

catalog_gmc_articuls:
  path:         /gmc/catalog/7
  defaults:     {_controller: CatalogGmcBundle:Catalog:articuls}
  requirements: {_method: POST}

catalog_gmc_group:
  path:         /gmc/catalog/8/{regionCode}/{modelCode}/{modificationCode}/{subGroupCode}/{token}
  defaults:     {_controller: CatalogGmcBundle:Catalog:getGroupBySubgroup}

#------------------------------------------------------------------------------

vin_gmc:
  path:         /gmc/vin/0/{token}
  defaults:     {_controller: CatalogGmcBundle:Vin:index, token: null}

vin_gmc_result:
  path:         /gmc/vin/1
  defaults:     {_controller: CatalogGmcBundle:Vin:result}
  requirements: {_method: POST}

vin_gmc_groups:
  path:         /gmc/vin/3/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{token}
  defaults:     {_controller: CatalogGmcBundle:Vin:groups, token: null}

vin_gmc_subgroups:
  path:         /gmc/vin/4/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{token}
  defaults:     {_controller: CatalogGmcBundle:Vin:subgroups, token: null}

vin_gmc_schemas:
  path:         /gmc/vin/5/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{token}
  defaults:     {_controller: CatalogGmcBundle:Vin:schemas, token: null}

vin_gmc_schema:
  path:         /gmc/vin/6/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{schemaCode}/{token}
  defaults:     {_controller: CatalogGmcBundle:Vin:schema, token: null}

vin_gmc_articuls:
  path:         /gmc/vin/7
  defaults:     {_controller: CatalogGmcBundle:Vin:vinarticuls}
  requirements: {_method: POST}

vin_gmc_group:
  path:         /gmc/vin/8/{regionCode}/{modelCode}/{modificationCode}/{subGroupCode}/{token}
  defaults:     {_controller: CatalogGmcBundle:Vin:getGroupBySubgroup}

#---------------------------------------------------------------------------------------------

articul_gmc:
  path:         /gmc/articul/0/{token}
  defaults:     {_controller: CatalogGmcBundle:Articul:index, token: null}

articul_gmc_find_token:
  path:         /gmc/articul/1/{token}/{regionCode}
  defaults:     {_controller: CatalogGmcBundle:Articul:findByArticul, regionCode: null}

articul_gmc_find:
  path:         /gmc/articul/2/{regionCode}
  defaults:     {_controller: CatalogGmcBundle:Articul:findByArticul, regionCode: null}

articul_gmc_modifications:
  path:         /gmc/articul/3
  defaults:     {_controller: CatalogGmcBundle:Articul:modifications}
  requirements: {_method: POST}

articul_gmc_complectations:
  path:         /gmc/articul/4/{regionCode}/{modelCode}/{modificationCode}/{articul}/{token}
  defaults:     {_controller: CatalogGmcBundle:Articul:gmcArticulComplectations, token: null}

articul_gmc_groups:
  path:         /gmc/articul/5/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{articul}/{token}
  defaults:     {_controller: CatalogGmcBundle:Articul:gmcArticulgroups, token: null}

articul_gmc_subgroups:
  path:         /gmc/articul/6/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{articul}/{token}
  defaults:     {_controller: CatalogGmcBundle:Articul:gmcArticulSubgroups, token: null}

articul_gmc_schemas:
  path:         /gmc/articul/7/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{articul}/{token}
  defaults:     {_controller: CatalogGmcBundle:Articul:gmcArticulSchemas, token: null}

articul_gmc_schema:
  path:         /gmc/articul/8/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{schemaCode}/{articul}/{token}
  defaults:     {_controller: CatalogGmcBundle:Articul:gmcArticulSchema, token: null}

articul_gmc_articuls:
  path:         /gmc/articul/9
  defaults:     {_controller: CatalogGmcBundle:Articul:gmcArticularticuls}
  requirements: {_method: POST}

articul_gmc_group:
  path:         /gmc/articul/8/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{subGroupCode}/{token}
  defaults:     {_controller: CatalogGmcBundle:Articul:getGroupBySubgroup}
catalog_gmc_homepage:
    path:     /hello/{name}
    defaults: { _controller: CatalogGmcBundle:Default:index }
