catalog_smart_token:
    path:         /smart/catalog/0/{token}/{regionCode}
    defaults:     {_controller: CatalogSmartBundle:Catalog:regionsModels, token: null, regionCode: null}

catalog_smart:
    path:         /smart/{regionCode}
    defaults:     {_controller: CatalogSmartBundle:Catalog:regionsModels, regionCode: null}

catalog_smart_modifications:
    path:         /smart/catalog/1
    defaults:     {_controller: CatalogSmartBundle:Catalog:modifications}
    requirements: {_method: POST}

catalog_smart_complectations:
    path:         /smart/catalog/2/{regionCode}/{modelCode}/{modificationCode}/{token}
    defaults:     {_controller: CatalogSmartBundle:Catalog:complectations, token: null}

catalog_smart_groups:
    path:         /smart/catalog/3/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{token}
    defaults:     {_controller: CatalogSmartBundle:Catalog:groups, token: null}

catalog_smart_subgroups:
    path:         /smart/catalog/4/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{token}
    defaults:     {_controller: CatalogSmartBundle:Catalog:subgroups, token: null}

catalog_smart_safirstlevelsubgroups:
    path:         /smart/catalog/41/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{sanum}/{token}
    defaults:     {_controller: CatalogSmartBundle:Catalog:saFirstLevelSubgroups, token: null}

catalog_smart_saschemas:
    path:         /smart/catalog/42/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{sanum}/{token}
    defaults:     {_controller: CatalogSmartBundle:Catalog:saSchemas, token: null}

catalog_smart_saschema:
    path:         /smart/catalog/43/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{sanum}/{schemaCode}/{token}
    defaults:     {_controller: CatalogSmartBundle:Catalog:saSchema, token: null}

catalog_smart_saarticuls:
    path:         /smart/catalog/44
    defaults:     {_controller: CatalogSmartBundle:Catalog:saArticuls}
    requirements: {_method: POST}

catalog_smart_schemas:
    path:         /smart/catalog/5/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{token}
    defaults:     {_controller: CatalogSmartBundle:Catalog:schemas, token: null}

catalog_smart_schema:
    path:         /smart/catalog/6/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{schemaCode}/{token}
    defaults:     {_controller: CatalogSmartBundle:Catalog:schema, token: null}

catalog_smart_articuls:
    path:         /smart/catalog/7
    defaults:     {_controller: CatalogSmartBundle:Catalog:articuls}
    requirements: {_method: POST}


  #----------------------------------------------------------------------------------

articul_smart:
    path:         /smart/articul/0/{token}
    defaults:     {_controller: CatalogSmartBundle:Articul:index, token: null}

articul_smart_find_token:
    path:         /smart/articul/1/{token}/{regionCode}
    defaults:     {_controller: CatalogSmartBundle:Articul:findByArticul, regionCode: null}

articul_smart_find:
    path:         /smart/articul/2/{regionCode}
    defaults:     {_controller: CatalogSmartBundle:Articul:findByArticul, regionCode: null}

articul_smart_modifications:
    path:         /smart/articul/3
    defaults:     {_controller: CatalogSmartBundle:Articul:modifications}
    requirements: {_method: POST}

articul_smart_complectations:
    path:         /smart/articul/4/{regionCode}/{modelCode}/{modificationCode}/{articul}/{token}
    defaults:     {_controller: CatalogSmartBundle:Articul:complectations, token: null}

articul_smart_groups:
    path:         /smart/articul/5/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{articul}/{token}
    defaults:     {_controller: CatalogSmartBundle:Articul:smartArticulGroups, token: null}

articul_smart_subgroups:
    path:         /smart/articul/6/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{articul}/{token}
    defaults:     {_controller: CatalogSmartBundle:Articul:smartArticulSubgroups, token: null}

articul_smart_safirstlevelsubgroups:
    path:         /smart/articul/41/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{sanum}/{articul}/{token}
    defaults:     {_controller: CatalogSmartBundle:Articul:saFirstLevelSubgroups, token: null}

articul_smart_saschemas:
    path:         /smart/articul/42/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{sanum}/{articul}/{token}
    defaults:     {_controller: CatalogSmartBundle:Articul:saSchemas, token: null}

articul_smart_saschema:
    path:         /smart/articul/43/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{sanum}/{schemaCode}/{articul}/{token}
    defaults:     {_controller: CatalogSmartBundle:Articul:saSchema, token: null}

articul_smart_saarticuls:
    path:         /smart/articul/44
    defaults:     {_controller: CatalogSmartBundle:Articul:saArticuls}
    requirements: {_method: POST}

articul_smart_schemas:
    path:         /smart/articul/7/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{articul}/{token}
    defaults:     {_controller: CatalogSmartBundle:Articul:smartArticulSchemas, token: null}

articul_smart_schema:
    path:         /smart/articul/8/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{schemaCode}/{articul}/{token}
    defaults:     {_controller: CatalogSmartBundle:Articul:smartArticulSchema, token: null}

articul_smart_articuls:
    path:         /smart/articul/9
    defaults:     {_controller: CatalogSmartBundle:Articul:articuls}
    requirements: {_method: POST}

  #-------------------------------------------------------------------------------------

vin_smart:
    path:         /smart/vin/0/{token}
    defaults:     {_controller: CatalogSmartBundle:Vin:index, token: null}

vin_smart_result:
    path:         /smart/vin/1
    defaults:     {_controller: CatalogSmartBundle:Vin:result}
    requirements: {_method: POST}

vin_smart_groups:
    path:         /smart/vin/3/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{token}
    defaults:     {_controller: CatalogSmartBundle:Vin:groups, token: null}

vin_smart_subgroups:
    path:         /smart/vin/4/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{token}
    defaults:     {_controller: CatalogSmartBundle:Vin:subgroups, token: null}

vin_smart_schemas:
    path:         /smart/vin/5/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{token}
    defaults:     {_controller: CatalogSmartBundle:Vin:schemas, token: null}

vin_smart_schema:
    path:         /smart/vin/6/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{schemaCode}/{token}
    defaults:     {_controller: CatalogSmartBundle:Vin:schema, token: null}

vin_smart_articuls:
    path:         /smart/vin/7
    defaults:     {_controller: CatalogSmartBundle:Vin:articuls}
    requirements: {_method: POST}