catalog_mercedes_token:
    path:         /mercedes/catalog/0/{token}/{regionCode}
    defaults:     {_controller: CatalogMercedesBundle:Catalog:regionsModels, token: null, regionCode: null}

catalog_mercedes:
    path:         /mercedes/{regionCode}
    defaults:     {_controller: CatalogMercedesBundle:Catalog:regionsModels, regionCode: null}

catalog_mercedes_modifications:
    path:         /mercedes/catalog/1
    defaults:     {_controller: CatalogMercedesBundle:Catalog:modifications}
    requirements: {_method: POST}

catalog_mercedes_complectations:
    path:         /mercedes/catalog/2/{regionCode}/{modelCode}/{modificationCode}/{token}
    defaults:     {_controller: CatalogMercedesBundle:Catalog:complectations, token: null}

catalog_mercedes_groups:
    path:         /mercedes/catalog/3/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{token}
    defaults:     {_controller: CatalogMercedesBundle:Catalog:groups, token: null}

catalog_mercedes_subgroups:
    path:         /mercedes/catalog/4/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{token}
    defaults:     {_controller: CatalogMercedesBundle:Catalog:subgroups, token: null}

catalog_mercedes_safirstlevelsubgroups:
    path:         /mercedes/catalog/41/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{sanum}/{token}
    defaults:     {_controller: CatalogMercedesBundle:Catalog:saFirstLevelSubgroups, token: null}

catalog_mercedes_saschemas:
    path:         /mercedes/catalog/42/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{sanum}/{token}
    defaults:     {_controller: CatalogMercedesBundle:Catalog:saSchemas, token: null}

catalog_mercedes_saschema:
    path:         /mercedes/catalog/43/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{sanum}/{schemaCode}/{token}
    defaults:     {_controller: CatalogMercedesBundle:Catalog:saSchema, token: null}

catalog_mercedes_saarticuls:
    path:         /mercedes/catalog/44
    defaults:     {_controller: CatalogMercedesBundle:Catalog:saArticuls}
    requirements: {_method: POST}

catalog_mercedes_schemas:
    path:         /mercedes/catalog/5/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{token}
    defaults:     {_controller: CatalogMercedesBundle:Catalog:schemas, token: null}

catalog_mercedes_schema:
    path:         /mercedes/catalog/6/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{schemaCode}/{token}
    defaults:     {_controller: CatalogMercedesBundle:Catalog:schema, token: null}

catalog_mercedes_articuls:
    path:         /mercedes/catalog/7
    defaults:     {_controller: CatalogMercedesBundle:Catalog:articuls}
    requirements: {_method: POST}


  #----------------------------------------------------------------------------------

articul_mercedes:
    path:         /mercedes/articul/0/{token}
    defaults:     {_controller: CatalogMercedesBundle:Articul:index, token: null}

articul_mercedes_find_token:
    path:         /mercedes/articul/1/{token}/{regionCode}
    defaults:     {_controller: CatalogMercedesBundle:Articul:findByArticul, regionCode: null}

articul_mercedes_find:
    path:         /mercedes/articul/2/{regionCode}
    defaults:     {_controller: CatalogMercedesBundle:Articul:findByArticul, regionCode: null}

articul_mercedes_modifications:
    path:         /mercedes/articul/3
    defaults:     {_controller: CatalogMercedesBundle:Articul:modifications}
    requirements: {_method: POST}

articul_mercedes_complectations:
    path:         /mercedes/articul/4/{regionCode}/{modelCode}/{modificationCode}/{articul}/{token}
    defaults:     {_controller: CatalogMercedesBundle:Articul:complectations, token: null}

articul_mercedes_groups:
    path:         /mercedes/articul/5/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{articul}/{token}
    defaults:     {_controller: CatalogMercedesBundle:Articul:mercedesArticulGroups, token: null}

articul_mercedes_subgroups:
    path:         /mercedes/articul/6/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{articul}/{token}
    defaults:     {_controller: CatalogMercedesBundle:Articul:mercedesArticulSubgroups, token: null}

articul_mercedes_safirstlevelsubgroups:
    path:         /mercedes/articul/41/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{sanum}/{articul}/{token}
    defaults:     {_controller: CatalogMercedesBundle:Articul:saFirstLevelSubgroups, token: null}

articul_mercedes_saschemas:
    path:         /mercedes/articul/42/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{sanum}/{articul}/{token}
    defaults:     {_controller: CatalogMercedesBundle:Articul:saSchemas, token: null}

articul_mercedes_saschema:
    path:         /mercedes/articul/43/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{sanum}/{schemaCode}/{articul}/{token}
    defaults:     {_controller: CatalogMercedesBundle:Articul:saSchema, token: null}

articul_mercedes_saarticuls:
    path:         /mercedes/articul/44
    defaults:     {_controller: CatalogMercedesBundle:Articul:saArticuls}
    requirements: {_method: POST}

articul_mercedes_schemas:
    path:         /mercedes/articul/7/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{articul}/{token}
    defaults:     {_controller: CatalogMercedesBundle:Articul:mercedesArticulSchemas, token: null}

articul_mercedes_schema:
    path:         /mercedes/articul/8/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{schemaCode}/{articul}/{token}
    defaults:     {_controller: CatalogMercedesBundle:Articul:mercedesArticulSchema, token: null}

articul_mercedes_articuls:
    path:         /mercedes/articul/9
    defaults:     {_controller: CatalogMercedesBundle:Articul:articuls}
    requirements: {_method: POST}

  #-------------------------------------------------------------------------------------

vin_mercedes:
    path:         /mercedes/vin/0/{token}
    defaults:     {_controller: CatalogMercedesBundle:Vin:index, token: null}

vin_mercedes_result:
    path:         /mercedes/vin/1
    defaults:     {_controller: CatalogMercedesBundle:Vin:result}
    requirements: {_method: POST}

vin_mercedes_groups:
    path:         /mercedes/vin/3/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{token}
    defaults:     {_controller: CatalogMercedesBundle:Vin:groups, token: null}

vin_mercedes_subgroups:
    path:         /mercedes/vin/4/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{token}
    defaults:     {_controller: CatalogMercedesBundle:Vin:subgroups, token: null}

vin_mercedes_schemas:
    path:         /mercedes/vin/5/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{token}
    defaults:     {_controller: CatalogMercedesBundle:Vin:schemas, token: null}

vin_mercedes_schema:
    path:         /mercedes/vin/6/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{schemaCode}/{token}
    defaults:     {_controller: CatalogMercedesBundle:Vin:schema, token: null}

vin_mercedes_articuls:
    path:         /mercedes/vin/7
    defaults:     {_controller: CatalogMercedesBundle:Vin:articuls}
    requirements: {_method: POST}