catalog_mercedes:
  path:         /mercedes/catalog/0/{regionCode}
  defaults:     {_controller: CatalogMercedesBundle:Catalog:regionsModels, regionCode: null}

catalog_mercedes_modifications:
  path:         /mercedes/catalog/1
  defaults:     {_controller: CatalogMercedesBundle:Catalog:modifications}
  requirements: {_method: POST}

catalog_mercedes_complectations:
  path:         /mercedes/catalog/2/{regionCode}/{modelCode}/{modificationCode}
  defaults:     {_controller: CatalogMercedesBundle:Catalog:complectations}

catalog_mercedes_groups:
  path:         /mercedes/catalog/3/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}
  defaults:     {_controller: CatalogMercedesBundle:Catalog:groups}

catalog_mercedes_subgroups:
  path:         /mercedes/catalog/4/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}
  defaults:     {_controller: CatalogMercedesBundle:Catalog:subgroups}

catalog_mercedes_schemas:
  path:         /mercedes/catalog/5/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}
  defaults:     {_controller: CatalogMercedesBundle:Catalog:schemas}