services:
#    catalog_mercedes.example:
#        class: Catalog\MercedesBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
  mercedes.catalog.model:
    class: Catalog\MercedesBundle\Models\MercedesCatalogModel
    arguments:  ['@doctrine.dbal.mercedes_connection']

  mercedes.articul.model:
    class: Catalog\MercedesBundle\Models\MercedesArticulModel
    arguments:  ['@doctrine.dbal.mercedes_connection']

  mercedes.vin.model:
    class: Catalog\MercedesBundle\Models\MercedesVinModel
    arguments:  ['@doctrine.dbal.mercedes_connection']

  mercedes_array_chunk.extension:
    class: Catalog\MercedesBundle\Twig\Extension\ArrayChunkExtension
    tags:
      - { name: twig.extension}