catalog_buick_token:
  path:         /buick/catalog/0/{token}/{regionCode}
  defaults:     {_controller: CatalogBuickBundle:Catalog:regionsModels, token: null, regionCode: null}

catalog_buick:
  path:         /buick/{regionCode}
  defaults:     {_controller: CatalogBuickBundle:Catalog:regionsModels, regionCode: null}

catalog_buick_modifications:
  path:         /buick/catalog/1
  defaults:     {_controller: CatalogBuickBundle:Catalog:modifications}
  requirements: {_method: POST}

catalog_buick_complectations:
  path:         /buick/catalog/2/{regionCode}/{modelCode}/{modificationCode}/{token}
  defaults:     {_controller: CatalogBuickBundle:Catalog:complectations, token: null}

catalog_buick_groups:
  path:         /buick/catalog/3/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{token}
  defaults:     {_controller: CatalogBuickBundle:Catalog:groups, token: null}

catalog_buick_subgroups:
  path:         /buick/catalog/4/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{token}
  defaults:     {_controller: CatalogBuickBundle:Catalog:subgroups, token: null}

catalog_buick_schemas:
  path:         /buick/catalog/5/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{token}
  defaults:     {_controller: CatalogBuickBundle:Catalog:schemas, token: null}

catalog_buick_schema:
  path:         /buick/catalog/6/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{schemaCode}/{token}
  defaults:     {_controller: CatalogBuickBundle:Catalog:schema, token: null}

catalog_buick_articuls:
  path:         /buick/catalog/7
  defaults:     {_controller: CatalogBuickBundle:Catalog:articuls}
  requirements: {_method: POST}

catalog_buick_group:
  path:         /buick/catalog/8/{regionCode}/{modelCode}/{modificationCode}/{subGroupCode}/{token}
  defaults:     {_controller: CatalogBuickBundle:Catalog:getGroupBySubgroup}

#------------------------------------------------------------------------------

vin_buick:
  path:         /buick/vin/0/{token}
  defaults:     {_controller: CatalogBuickBundle:Vin:index, token: null}

vin_buick_result:
  path:         /buick/vin/1
  defaults:     {_controller: CatalogBuickBundle:Vin:result}
  requirements: {_method: POST}

vin_buick_groups:
  path:         /buick/vin/3/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{token}
  defaults:     {_controller: CatalogBuickBundle:Vin:groups, token: null}

vin_buick_subgroups:
  path:         /buick/vin/4/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{token}
  defaults:     {_controller: CatalogBuickBundle:Vin:subgroups, token: null}

vin_buick_schemas:
  path:         /buick/vin/5/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{token}
  defaults:     {_controller: CatalogBuickBundle:Vin:schemas, token: null}

vin_buick_schema:
  path:         /buick/vin/6/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{schemaCode}/{token}
  defaults:     {_controller: CatalogBuickBundle:Vin:schema, token: null}

vin_buick_articuls:
  path:         /buick/vin/7
  defaults:     {_controller: CatalogBuickBundle:Vin:vinarticuls}
  requirements: {_method: POST}

vin_buick_group:
  path:         /buick/vin/8/{regionCode}/{modelCode}/{modificationCode}/{subGroupCode}/{token}
  defaults:     {_controller: CatalogBuickBundle:Vin:getGroupBySubgroup}

#---------------------------------------------------------------------------------------------

articul_buick:
  path:         /buick/articul/0/{token}
  defaults:     {_controller: CatalogBuickBundle:Articul:index, token: null}

articul_buick_find_token:
  path:         /buick/articul/1/{token}/{regionCode}
  defaults:     {_controller: CatalogBuickBundle:Articul:findByArticul, regionCode: null}

articul_buick_find:
  path:         /buick/articul/2/{regionCode}
  defaults:     {_controller: CatalogBuickBundle:Articul:findByArticul, regionCode: null}

articul_buick_modifications:
  path:         /buick/articul/3
  defaults:     {_controller: CatalogBuickBundle:Articul:modifications}
  requirements: {_method: POST}

articul_buick_complectations:
  path:         /buick/articul/4/{regionCode}/{modelCode}/{modificationCode}/{articul}/{token}
  defaults:     {_controller: CatalogBuickBundle:Articul:buickArticulComplectations, token: null}

articul_buick_groups:
  path:         /buick/articul/5/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{articul}/{token}
  defaults:     {_controller: CatalogBuickBundle:Articul:buickArticulgroups, token: null}

articul_buick_subgroups:
  path:         /buick/articul/6/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{articul}/{token}
  defaults:     {_controller: CatalogBuickBundle:Articul:buickArticulSubgroups, token: null}

articul_buick_schemas:
  path:         /buick/articul/7/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{articul}/{token}
  defaults:     {_controller: CatalogBuickBundle:Articul:buickArticulSchemas, token: null}

articul_buick_schema:
  path:         /buick/articul/8/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{schemaCode}/{articul}/{token}
  defaults:     {_controller: CatalogBuickBundle:Articul:buickArticulSchema, token: null}

articul_buick_articuls:
  path:         /buick/articul/9
  defaults:     {_controller: CatalogBuickBundle:Articul:buickArticularticuls}
  requirements: {_method: POST}

articul_buick_group:
  path:         /buick/articul/8/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{subGroupCode}/{token}
  defaults:     {_controller: CatalogBuickBundle:Articul:getGroupBySubgroup}
catalog_buick_homepage:
    path:     /hello/{name}
    defaults: { _controller: CatalogBuickBundle:Default:index }
