services:
#    catalog_common.example:
#        class: Catalog\CommonBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
  date_convertor.extension:
        class: Catalog\CommonBundle\Twig\Extension\DateConvertorExtension
        arguments: ["@request_stack"]
        tags:
            - { name: twig.extension}

  md5.extension:
        class: Catalog\CommonBundle\Twig\Extension\Md5Extension
        tags:
            - { name: twig.extension}
  file_exists.extension:
        class: Catalog\CommonBundle\Twig\Extension\FileExistsExtension
        tags:
            - { name: twig.extension}