imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
      types:
        json: Sonata\Doctrine\Types\JsonType
      default_connection: mitsubishi
      connections:
        mitsubishi:
          dbname:   "%database_name%"
          user:     "%database_user%"
          password: "%database_password%"
          charset:  UTF8
          driver:   "%database_driver%"
          host:     "%database_host%"
          port:     "%database_port%"
        mazda:
          dbname:   mazda
          user:     catsmitsuby
          password: vY6hMc7kfSIOt3O
          charset:  UTF8
          driver:   "%database_driver%"
          host:     suraman.newsolution.by
          port:     "%database_port%"
        subaru:
          dbname:   subaru
          user:     catsmitsuby
          password: vY6hMc7kfSIOt3O
          charset:  UTF8
          driver:   "%database_driver%"
          host:     "%database_host%"
          port:     "%database_port%"
        mercedes:
          dbname:   mercedesbenz
          user:     catsmitsuby
          password: vY6hMc7kfSIOt3O
          charset:  UTF8
          driver:   "%database_driver%"
          host:     suraman.newsolution.by
        smart:
          dbname:   mercedesbenz
          user:     catsmitsuby
          password: vY6hMc7kfSIOt3O
          charset:  UTF8
          driver:   "%database_driver%"
          host:     suraman.newsolution.by
        suzuki:
          dbname:   suzuki
          user:     catsmitsuby
          password: vY6hMc7kfSIOt3O
          charset:  UTF8
          driver:   "%database_driver%"
          host:     localhost
          port:     "%database_port%"
        honda:
          dbname:   honda
          user:     catsmitsuby
          password: vY6hMc7kfSIOt3O
          charset:  UTF8
          driver:   "%database_driver%"
          host:     suraman.newsolution.by
          port:     "%database_port%"
        hondaeurope:
          dbname:   hondaeurope
          user:     catsmitsuby
          password: vY6hMc7kfSIOt3O
          charset:  UTF8
          driver:   "%database_driver%"
          host:     suraman.newsolution.by
          port:     "%database_port%"
        huyndai:
          dbname:   huyndai
          user:     catsmitsuby
          password: vY6hMc7kfSIOt3O
          charset:  UTF8
          driver:   "%database_driver%"
          host:     suraman.newsolution.by
          port:     "%database_port%"
        kia:
          dbname:   kia
          user:     catsmitsuby
          password: vY6hMc7kfSIOt3O
          charset:  UTF8
          driver:   "%database_driver%"
          host:     suraman.newsolution.by
          port:     "%database_port%"

        bmw:
          dbname:   bmw
          user:     catsmitsuby
          password: vY6hMc7kfSIOt3O
          charset:  UTF8
          driver:   "%database_driver%"
          host:     suraman.newsolution.by
          port:     "%database_port%"

        saab:
          dbname:   saab
          user:     catsmitsuby
          password: vY6hMc7kfSIOt3O
          charset:  UTF8
          driver:   "%database_driver%"
          host:     suraman.newsolution.by
          port:     "%database_port%"

        ford:
          dbname:   epc_ford
          user:     catsmitsuby
          password: vY6hMc7kfSIOt3O
          charset:  UTF8
          driver:   "%database_driver%"
          host:     suraman.newsolution.by
          port:     "%database_port%"

        audi:
          dbname:   vag_etka
          user:     catsmitsuby
          password: vY6hMc7kfSIOt3O
          charset:  UTF8
          driver:   "%database_driver%"
          host:     suraman.newsolution.by
          port:     "%database_port%"

        volkswagen:
          dbname:   vag_etka
          user:     catsmitsuby
          password: vY6hMc7kfSIOt3O
          charset:  UTF8
          driver:   "%database_driver%"
          host:     suraman.newsolution.by
          port:     "%database_port%"

        skoda:
          dbname:   vag_etka
          user:     catsmitsuby
          password: vY6hMc7kfSIOt3O
          charset:  UTF8
          driver:   "%database_driver%"
          host:     suraman.newsolution.by
          port:     "%database_port%"
        seat:
          dbname:   vag_etka
          user:     catsmitsuby
          password: vY6hMc7kfSIOt3O
          charset:  UTF8
          driver:   "%database_driver%"
          host:     suraman.newsolution.by
          port:     "%database_port%"

        fiat:
          dbname:   fiat_eper
          user:     catsmitsuby
          password: vY6hMc7kfSIOt3O
          charset:  UTF8
          driver:   "%database_driver%"
          host:     suraman.newsolution.by
          port:     "%database_port%"

        lancia:
          dbname:   fiat_eper
          user:     catsmitsuby
          password: vY6hMc7kfSIOt3O
          charset:  UTF8
          driver:   "%database_driver%"
          host:     suraman.newsolution.by
          port:     "%database_port%"

        alfaromeo:
          dbname:   fiat_eper
          user:     catsmitsuby
          password: vY6hMc7kfSIOt3O
          charset:  UTF8
          driver:   "%database_driver%"
          host:     suraman.newsolution.by
          port:     "%database_port%"

        fiatprofessional:
          dbname:   fiat_eper
          user:     catsmitsuby
          password: vY6hMc7kfSIOt3O
          charset:  UTF8
          driver:   "%database_driver%"
          host:     suraman.newsolution.by
          port:     "%database_port%"

        abarth:
          dbname:   fiat_eper
          user:     catsmitsuby
          password: vY6hMc7kfSIOt3O
          charset:  UTF8
          driver:   "%database_driver%"
          host:     suraman.newsolution.by
          port:     "%database_port%"

        chevroletusa:
          dbname:   gmna
          user:     catsmitsuby
          password: vY6hMc7kfSIOt3O
          charset:  UTF8
          driver:   "%database_driver%"
          host:     suraman.newsolution.by
          port:     "%database_port%"

        nissan:
          dbname:   nissan_fast
          user:     root
          password: 123456
          charset:  UTF8
          driver:   "%database_driver%"
          host:     localhost
          port:     "%database_port%"

        infiniti:
          dbname:   nissan_fast
          user:     root
          password: 123456
          charset:  UTF8
          driver:   "%database_driver%"
          host:     localhost
          port:     "%database_port%"

        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
      auto_generate_proxy_classes: "%kernel.debug%"
      auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }