catalog_volkswagen:
    resource: "@CatalogVolkswagenBundle/Resources/config/routing.yml"
    prefix:   /

catalog_audi:
    resource: "@CatalogAudiBundle/Resources/config/routing.yml"
    prefix:   /

catalog_ford:
    resource: "@CatalogFordBundle/Resources/config/routing.yml"
    prefix:   /

catalog_saab:
    resource: "@CatalogSaabBundle/Resources/config/routing.yml"
    prefix:   /

acme_task:
    resource: "@AcmeTaskBundle/Resources/config/routing.php"
    prefix:   /

catalog_subaru:
    resource: "@CatalogSubaruBundle/Resources/config/routing.yml"
    prefix:   /

catalog_mercedes:
    resource: "@CatalogMercedesBundle/Resources/config/routing.yml"
    prefix:   /

catalog_common:
    resource: "@CatalogCommonBundle/Resources/config/routing.yml"
    prefix:   /

catalog_mazda:
    resource: "@CatalogMazdaBundle/Resources/config/routing.yml"
    prefix:   /

catalog_mitsubishi:
    resource: "@CatalogMitsubishiBundle/Resources/config/routing.yml"
    prefix:   /
    
catalog_suzuki:
    resource: "@CatalogSuzukiBundle/Resources/config/routing.yml"
    prefix:   /
    
catalog_honda:
    resource: "@CatalogHondaBundle/Resources/config/routing.yml"
    prefix:   /

catalog_hondaeurope:
    resource: "@CatalogHondaEuropeBundle/Resources/config/routing.yml"
    prefix:   /

catalog_huyndai:
    resource: "@CatalogHuyndaiBundle/Resources/config/routing.yml"
    prefix:   /

catalog_kia:
    resource: "@CatalogKiaBundle/Resources/config/routing.yml"
    prefix:   /

catalog_bmw:
    resource: "@CatalogBmwBundle/Resources/config/routing.yml"
    prefix:   /

catalog_mini:
    resource: "@CatalogMiniBundle/Resources/config/routing.yml"
    prefix:   /

catalog_rollsroyce:
    resource: "@CatalogRollsRoyceBundle/Resources/config/routing.yml"
    prefix:   /