acme_billing:
    resource: "@AcmeBillingBundle/Resources/config/routing.yml"
    prefix:   /

catalog_lexus:
    resource: "@CatalogLexusBundle/Resources/config/routing.yml"
    prefix:   /

catalog_toyota:
    resource: "@CatalogToyotaBundle/Resources/config/routing.yml"
    prefix:   /

catalog_volvo:
    resource: "@CatalogVolvoBundle/Resources/config/routing.yml"
    prefix:   /

catalog_landrover:
    resource: "@CatalogLandRoverBundle/Resources/config/routing.yml"
    prefix:   /

catalog_infiniti:
    resource: "@CatalogInfinitiBundle/Resources/config/routing.yml"
    prefix:   /

catalog_nissan:
    resource: "@CatalogNissanBundle/Resources/config/routing.yml"
    prefix:   /

catalog_chevroletusa:
    resource: "@CatalogChevroletUsaBundle/Resources/config/routing.yml"
    prefix:   /

catalog_pontiac:
    resource: "@CatalogPontiacBundle/Resources/config/routing.yml"
    prefix:   /

catalog_cadillac:
    resource: "@CatalogCadillacBundle/Resources/config/routing.yml"
    prefix:   /

catalog_buick:
    resource: "@CatalogBuickBundle/Resources/config/routing.yml"
    prefix:   /

catalog_hummer:
    resource: "@CatalogHummerBundle/Resources/config/routing.yml"
    prefix:   /

catalog_saturn:
    resource: "@CatalogSaturnBundle/Resources/config/routing.yml"
    prefix:   /

catalog_gmc:
    resource: "@CatalogGmcBundle/Resources/config/routing.yml"
    prefix:   /

catalog_oldsmobile:
    resource: "@CatalogOldsmobileBundle/Resources/config/routing.yml"
    prefix:   /

catalog_abarth:
    resource: "@CatalogAbarthBundle/Resources/config/routing.yml"
    prefix:   /

catalog_fiatprofessional:
    resource: "@CatalogFiatProfessionalBundle/Resources/config/routing.yml"
    prefix:   /

catalog_alfaromeo:
    resource: "@CatalogAlfaRomeoBundle/Resources/config/routing.yml"
    prefix:   /

catalog_lancia:
    resource: "@CatalogLanciaBundle/Resources/config/routing.yml"
    prefix:   /

catalog_fiat:
    resource: "@CatalogFiatBundle/Resources/config/routing.yml"
    prefix:   /

catalog_seat:
    resource: "@CatalogSeatBundle/Resources/config/routing.yml"
    prefix:   /

catalog_skoda:
    resource: "@CatalogSkodaBundle/Resources/config/routing.yml"
    prefix:   /

catalog_volkswagen:
    resource: "@CatalogVolkswagenBundle/Resources/config/routing.yml"
    prefix:   /

catalog_audi:
    resource: "@CatalogAudiBundle/Resources/config/routing.yml"
    prefix:   /

catalog_ford:
    resource: "@CatalogFordBundle/Resources/config/routing.yml"
    prefix:   /

catalog_saab:
    resource: "@CatalogSaabBundle/Resources/config/routing.yml"
    prefix:   /

acme_task:
    resource: "@AcmeTaskBundle/Resources/config/routing.php"
    prefix:   /

acme_billing:
    resource: "@AcmeBillingBundle/Resources/config/routing.yml"
    prefix:   /

catalog_subaru:
    resource: "@CatalogSubaruBundle/Resources/config/routing.yml"
    prefix:   /

catalog_mercedes:
    resource: "@CatalogMercedesBundle/Resources/config/routing.yml"
    prefix:   /

catalog_smart:
    resource: "@CatalogSmartBundle/Resources/config/routing.yml"
    prefix:   /

catalog_common:
    resource: "@CatalogCommonBundle/Resources/config/routing.yml"
    prefix:   /

catalog_mazda:
    resource: "@CatalogMazdaBundle/Resources/config/routing.yml"
    prefix:   /

catalog_mitsubishi:
    resource: "@CatalogMitsubishiBundle/Resources/config/routing.yml"
    prefix:   /
    
catalog_suzuki:
    resource: "@CatalogSuzukiBundle/Resources/config/routing.yml"
    prefix:   /
    
catalog_honda:
    resource: "@CatalogHondaBundle/Resources/config/routing.yml"
    prefix:   /

catalog_hondaeurope:
    resource: "@CatalogHondaEuropeBundle/Resources/config/routing.yml"
    prefix:   /

catalog_huyndai:
    resource: "@CatalogHuyndaiBundle/Resources/config/routing.yml"
    prefix:   /

catalog_kia:
    resource: "@CatalogKiaBundle/Resources/config/routing.yml"
    prefix:   /

catalog_bmw:
    resource: "@CatalogBmwBundle/Resources/config/routing.yml"
    prefix:   /

catalog_mini:
    resource: "@CatalogMiniBundle/Resources/config/routing.yml"
    prefix:   /

catalog_rollsroyce:
    resource: "@CatalogRollsRoyceBundle/Resources/config/routing.yml"
    prefix:   /