catalog_subaru:
    resource: "@CatalogSubaruBundle/Resources/config/routing.yml"
    prefix:   /

catalog_mercedes:
    resource: "@CatalogMercedesBundle/Resources/config/routing.yml"
    prefix:   /

catalog_common:
    resource: "@CatalogCommonBundle/Resources/config/routing.yml"
    prefix:   /

catalog_mazda:
    resource: "@CatalogMazdaBundle/Resources/config/routing.yml"
    prefix:   /

catalog_mitsubishi:
    resource: "@CatalogMitsubishiBundle/Resources/config/routing.yml"
    prefix:   /

