acme_task:
    resource: "@AcmeTaskBundle/Resources/config/routing.php"
    prefix:   /

catalog_subaru:
    resource: "@CatalogSubaruBundle/Resources/config/routing.yml"
    prefix:   /

catalog_mercedes:
    resource: "@CatalogMercedesBundle/Resources/config/routing.yml"
    prefix:   /

catalog_common:
    resource: "@CatalogCommonBundle/Resources/config/routing.yml"
    prefix:   /

catalog_mazda:
    resource: "@CatalogMazdaBundle/Resources/config/routing.yml"
    prefix:   /

catalog_mitsubishi:
    resource: "@CatalogMitsubishiBundle/Resources/config/routing.yml"
    prefix:   /
    
catalog_suzuki:
    resource: "@CatalogSuzukiBundle/Resources/config/routing.yml"
    prefix:   /
    
catalog_honda:
    resource: "@CatalogHondaBundle/Resources/config/routing.yml"
    prefix:   /

catalog_huyndai:
    resource: "@CatalogHuyndaiBundle/Resources/config/routing.yml"
    prefix:   /

catalog_kia:
    resource: "@CatalogKiaBundle/Resources/config/routing.yml"
    prefix:   /

catalog_bmw:
    resource: "@CatalogBmvBundle/Resources/config/routing.yml"
    prefix:   /

catalog_mini:
    resource: "@CatalogMiniBundle/Resources/config/routing.yml"
    prefix:   /

catalog_rollsroyce:
    resource: "@CatalogRollsRoyceBundle/Resources/config/routing.yml"
    prefix:   /

# FOSUserBundle's routing
fos_user_security:
  resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
  resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
  prefix: /profile

fos_user_register:
  resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
  prefix: /register

fos_user_resetting:
  resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
  prefix: /resetting

fos_user_change_password:
  resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
  prefix: /profile

# Admin's routing
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

soanata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin