catalog_huyndai_token:
  path:         /huyndai/catalog/0/{token}/{regionCode}
  defaults:     {_controller: CatalogHuyndaiBundle:Catalog:regionsModels, token: null, regionCode: null}

catalog_huyndai:
  path:         /huyndai/{regionCode}
  defaults:     {_controller: CatalogHuyndaiBundle:Catalog:regionsModels, regionCode: null}

catalog_huyndai_modifications:
  path:         /huyndai/catalog/1
  defaults:     {_controller: CatalogHuyndaiBundle:Catalog:modifications}
  requirements: {_method: POST}

catalog_huyndai_complectations:
  path:         /huyndai/catalog/2/{regionCode}/{modelCode}/{modificationCode}/{token}
  defaults:     {_controller: CatalogHuyndaiBundle:Catalog:complectations, token: null}

catalog_huyndai_groups:
  path:         /huyndai/catalog/3/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{token}
  defaults:     {_controller: CatalogHuyndaiBundle:Catalog:groups, token: null}

catalog_huyndai_subgroups:
  path:         /huyndai/catalog/4/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{token}
  defaults:     {_controller: CatalogHuyndaiBundle:Catalog:subgroups, token: null}

catalog_huyndai_schemas:
  path:         /huyndai/catalog/5/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{token}
  defaults:     {_controller: CatalogHuyndaiBundle:Catalog:schemas, token: null}

catalog_huyndai_schema:
  path:         /huyndai/catalog/6/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{schemaCode}/{token}
  defaults:     {_controller: CatalogHuyndaiBundle:Catalog:schema, token: null}


catalog_huyndai_articuls:
  path:         /huyndai/catalog/7
  defaults:     {_controller: CatalogHuyndaiBundle:Catalog:articuls}
  requirements: {_method: POST}

catalog_huyndai_group:
  path:         /huyndai/catalog/8/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{subGroupCode}/{token}
  defaults:     {_controller: CatalogHuyndaiBundle:Catalog:getGroupBySubgroup}

#------------------------------------------------------------------------------

vin_huyndai:
  path:         /huyndai/vin/0/{token}
  defaults:     {_controller: CatalogHuyndaiBundle:Vin:index, token: null}

vin_huyndai_result:
  path:         /huyndai/vin/1
  defaults:     {_controller: CatalogHuyndaiBundle:Vin:result}
  requirements: {_method: POST}

vin_huyndai_groups:
  path:         /huyndai/vin/3/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{token}
  defaults:     {_controller: CatalogHuyndaiBundle:Vin:groups, token: null}

vin_huyndai_subgroups:
  path:         /huyndai/vin/4/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{token}
  defaults:     {_controller: CatalogHuyndaiBundle:Vin:vinSubgroups, token: null}

vin_huyndai_schemas:
  path:         /huyndai/vin/5/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{token}
  defaults:     {_controller: CatalogHuyndaiBundle:Vin:schemas, token: null}

vin_huyndai_schema:
  path:         /huyndai/vin/6/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{schemaCode}/{token}
  defaults:     {_controller: CatalogHuyndaiBundle:Vin:schema, token: null}

vin_huyndai_articuls:
  path:         /huyndai/vin/7
  defaults:     {_controller: CatalogHuyndaiBundle:Vin:articuls}
  requirements: {_method: POST}

vin_huyndai_group:
  path:         /huyndai/vin/8/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{subGroupCode}/{token}
  defaults:     {_controller: CatalogHuyndaiBundle:Vin:getGroupBySubgroup}

#---------------------------------------------------------------------------------------------

articul_huyndai:
  path:         /huyndai/articul/0/{token}
  defaults:     {_controller: CatalogHuyndaiBundle:Articul:index, token: null}

articul_huyndai_find_token:
  path:         /huyndai/articul/1/{token}/{regionCode}
  defaults:     {_controller: CatalogHuyndaiBundle:Articul:findByArticul, regionCode: null}

articul_huyndai_find:
  path:         /huyndai/articul/2/{regionCode}
  defaults:     {_controller: CatalogHuyndaiBundle:Articul:findByArticul, regionCode: null}

articul_huyndai_modifications:
  path:         /huyndai/articul/3
  defaults:     {_controller: CatalogHuyndaiBundle:Articul:modifications}
  requirements: {_method: POST}

articul_huyndai_complectations:
  path:         /huyndai/articul/4/{regionCode}/{modelCode}/{modificationCode}/{articul}/{token}
  defaults:     {_controller: CatalogHuyndaiBundle:Articul:huyndaiArticulComplectations, token: null}

articul_huyndai_groups:
  path:         /huyndai/articul/5/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{articul}/{token}
  defaults:     {_controller: CatalogHuyndaiBundle:Articul:huyndaiArticulgroups, token: null}

articul_huyndai_subgroups:
  path:         /huyndai/articul/6/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{articul}/{token}
  defaults:     {_controller: CatalogHuyndaiBundle:Articul:huyndaiArticulSubgroups, token: null}

articul_huyndai_schemas:
  path:         /huyndai/articul/7/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{articul}/{token}
  defaults:     {_controller: CatalogHuyndaiBundle:Articul:huyndaiArticulSchemas, token: null}

articul_huyndai_schema:
  path:         /huyndai/articul/8/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{schemaCode}/{articul}/{token}
  defaults:     {_controller: CatalogHuyndaiBundle:Articul:huyndaiArticulSchema, token: null}

articul_huyndai_articuls:
  path:         /huyndai/articul/9
  defaults:     {_controller: CatalogHuyndaiBundle:Articul:articuls}
  requirements: {_method: POST}

articul_huyndai_group:
  path:         /huyndai/articul/8/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{subGroupCode}/{token}
  defaults:     {_controller: CatalogHuyndaiBundle:Articul:getGroupBySubgroup}
