catalog_lexus:
  path:         /lexus/catalog/0/{regionCode}
  defaults:     {_controller: CatalogLexusBundle:Catalog:regionsModels, regionCode: null}

catalog_lexus_modifications:
  path:         /lexus/catalog/1
  defaults:     {_controller: CatalogLexusBundle:Catalog:modifications}
  requirements: {_method: POST}

catalog_lexus_complectations:
  path:         /lexus/catalog/2/{regionCode}/{modelCode}/{modificationCode}
  defaults:     {_controller: CatalogLexusBundle:Catalog:complectations}

catalog_lexus_groups:
  path:         /lexus/catalog/3/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}
  defaults:     {_controller: CatalogLexusBundle:Catalog:groups}

catalog_lexus_subgroups:
  path:         /lexus/catalog/4/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}
  defaults:     {_controller: CatalogLexusBundle:Catalog:subgroups}

catalog_lexus_schemas:
  path:         /lexus/catalog/5/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}
  defaults:     {_controller: CatalogLexusBundle:Catalog:schemas}

catalog_lexus_schema:
  path:         /lexus/catalog/6/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{schemaCode}
  defaults:     {_controller: CatalogLexusBundle:Catalog:schema}

catalog_lexus_articuls:
  path:         /lexus/catalog/7
  defaults:     {_controller: CatalogLexusBundle:Catalog:articuls}
  requirements: {_method: POST}

catalog_lexus_group:
  path:         /lexus/catalog/8/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{subGroupCode}
  defaults:     {_controller: CatalogLexusBundle:Catalog:getGroupBySubgroup}

#------------------------------------------------------------------------------

vin_lexus:
  path:         /lexus/vin/0
  defaults:     {_controller: CatalogLexusBundle:Vin:index}

vin_lexus_result:
  path:         /lexus/vin/1
  defaults:     {_controller: CatalogLexusBundle:Vin:result}
  requirements: {_method: POST}

vin_lexus_groups:
  path:         /lexus/vin/3/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}
  defaults:     {_controller: CatalogLexusBundle:Vin:groups}

vin_lexus_subgroups:
  path:         /lexus/vin/4/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}
  defaults:     {_controller: CatalogLexusBundle:Vin:subgroups}

vin_lexus_schemas:
  path:         /lexus/vin/5/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}
  defaults:     {_controller: CatalogLexusBundle:Vin:schemas}

vin_lexus_schema:
  path:         /lexus/vin/6/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{schemaCode}
  defaults:     {_controller: CatalogLexusBundle:Vin:schema}

vin_lexus_articuls:
  path:         /lexus/vin/7
  defaults:     {_controller: CatalogLexusBundle:Vin:articuls}
  requirements: {_method: POST}

vin_lexus_group:
  path:         /lexus/vin/8/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{subGroupCode}
  defaults:     {_controller: CatalogLexusBundle:Vin:vinGroupBySubgroup}

#---------------------------------------------------------------------------------------------

articul_lexus:
  path:         /lexus/articul/0
  defaults:     {_controller: CatalogLexusBundle:Articul:index}

articul_lexus_find:
  path:         /lexus/articul/1/{regionCode}
  defaults:     {_controller: CatalogLexusBundle:Articul:findByArticul, regionCode: null}

articul_lexus_modifications:
  path:         /lexus/articul/3
  defaults:     {_controller: CatalogLexusBundle:Articul:modifications}
  requirements: {_method: POST}

articul_lexus_complectations:
  path:         /lexus/articul/4/{regionCode}/{modelCode}/{modificationCode}
  defaults:     {_controller: CatalogLexusBundle:Articul:lexusArticulComplectations}

articul_lexus_groups:
  path:         /lexus/articul/5/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}
  defaults:     {_controller: CatalogLexusBundle:Articul:lexusArticulgroups}

articul_lexus_subgroups:
  path:         /lexus/articul/6/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}
  defaults:     {_controller: CatalogLexusBundle:Articul:lexusArticulSubgroups}

articul_lexus_schemas:
  path:         /lexus/articul/7/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}
  defaults:     {_controller: CatalogLexusBundle:Articul:lexusArticulSchemas}

articul_lexus_schema:
  path:         /lexus/articul/8/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{schemaCode}
  defaults:     {_controller: CatalogLexusBundle:Articul:lexusArticulSchema}

articul_lexus_articuls:
  path:         /lexus/articul/9
  defaults:     {_controller: CatalogLexusBundle:Articul:articuls}
  requirements: {_method: POST}

articul_lexus_group:
  path:         /lexus/articul/8/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{subGroupCode}
  defaults:     {_controller: CatalogLexusBundle:Articul:getGroupBySubgroup}
catalog_lexus_homepage:
    path:     /hello/{name}
    defaults: { _controller: CatalogLexusBundle:Default:index }
