catalog_lexus_token:
  path:         /lexus/catalog/0/{token}/{_locale}/{regionCode}
  defaults:     {_controller: CatalogLexusBundle:Catalog:regionsModels, _locale: ru, token: null, regionCode: null}

catalog_lexus:
  path:         /lexus/{_locale}/{regionCode}
  defaults:     {_controller: CatalogLexusBundle:Catalog:regionsModels, _locale: ru, regionCode: null}

catalog_lexus_modifications:
  path:         /lexus/{_locale}/catalog/1
  defaults:     {_controller: CatalogLexusBundle:Catalog:modifications}
  requirements: {_method: POST}

catalog_lexus_complectations:
  path:         /lexus/{_locale}/catalog/2/{regionCode}/{modelCode}/{modificationCode}/{token}
  defaults:     {_controller: CatalogLexusBundle:Catalog:complectations, token: null}

catalog_lexus_complectation_korobka:
  path:         /lexus/{_locale}/catalog/12
  defaults:     {_controller: CatalogLexusBundle:Catalog:complectation_korobka}
  requirements: {_method: POST}

catalog_lexus_groups:
  path:         /lexus/{_locale}/catalog/3/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{token}
  defaults:     {_controller: CatalogLexusBundle:Catalog:groups, token: null}

catalog_lexus_subgroups:
  path:         /lexus/{_locale}/catalog/4/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{token}
  defaults:     {_controller: CatalogLexusBundle:Catalog:subgroups, token: null}

catalog_lexus_schemas:
  path:         /lexus/{_locale}/catalog/5/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{token}
  defaults:     {_controller: CatalogLexusBundle:Catalog:schemas, token: null}

catalog_lexus_schema:
  path:         /lexus/{_locale}/catalog/6/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{schemaCode}/{token}
  defaults:     {_controller: CatalogLexusBundle:Catalog:schema, token: null}

catalog_lexus_articuls:
  path:         /lexus/{_locale}/catalog/7
  defaults:     {_controller: CatalogLexusBundle:Catalog:articuls}
  requirements: {_method: POST}

catalog_lexus_group:
  path:         /lexus/{_locale}/catalog/8/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{subGroupCode}/{token}
  defaults:     {_controller: CatalogLexusBundle:Catalog:getGroupBySubgroup, token: null}

#------------------------------------------------------------------------------

vin_lexus:
  path:         /lexus/{_locale}/vin/0/{token}
  defaults:     {_controller: CatalogLexusBundle:Vin:index, token: null}

vin_lexus_result:
  path:         /lexus/{_locale}/vin/1
  defaults:     {_controller: CatalogLexusBundle:Vin:result}
  requirements: {_method: POST}

vin_lexus_groups:
  path:         /lexus/{_locale}/vin/3/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{token}
  defaults:     {_controller: CatalogLexusBundle:Vin:groups, token: null}

vin_lexus_subgroups:
  path:         /lexus/{_locale}/vin/4/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{token}
  defaults:     {_controller: CatalogLexusBundle:Vin:subgroups, token: null}

vin_lexus_schemas:
  path:         /lexus/{_locale}/vin/5/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{token}
  defaults:     {_controller: CatalogLexusBundle:Vin:schemas, token: null}

vin_lexus_schema:
  path:         /lexus/{_locale}/vin/6/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{schemaCode}/{token}
  defaults:     {_controller: CatalogLexusBundle:Vin:schema, token: null}

vin_lexus_articuls:
  path:         /lexus/{_locale}/vin/7
  defaults:     {_controller: CatalogLexusBundle:Vin:articuls}
  requirements: {_method: POST}

vin_lexus_group:
  path:         /lexus/{_locale}/vin/8/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{subGroupCode}/{token}
  defaults:     {_controller: CatalogLexusBundle:Vin:vinGroupBySubgroup, token: null}

#---------------------------------------------------------------------------------------------

articul_lexus:
  path:         /lexus/{_locale}/articul/0/{token}
  defaults:     {_controller: CatalogLexusBundle:Articul:index, token: null}

articul_lexus_find_token:
  path:         /lexus/{_locale}/articul/1/{token}/{regionCode}
  defaults:     {_controller: CatalogLexusBundle:Articul:findByArticul, token: null, regionCode: null}

articul_lexus_find:
  path:         /lexus/{_locale}/articul/2/{regionCode}
  defaults:     {_controller: CatalogLexusBundle:Articul:findByArticul, regionCode: null}

articul_lexus_modifications:
  path:         /lexus/{_locale}/articul/3
  defaults:     {_controller: CatalogLexusBundle:Articul:modifications}
  requirements: {_method: POST}

articul_lexus_complectations:
  path:         /lexus/{_locale}/articul/4/{regionCode}/{modelCode}/{modificationCode}/{articul}/{token}
  defaults:     {_controller: CatalogLexusBundle:Articul:lexusArticulComplectations, token: null}

articul_lexus_groups:
  path:         /lexus/{_locale}/articul/5/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{articul}/{token}
  defaults:     {_controller: CatalogLexusBundle:Articul:lexusArticulgroups, token: null}

articul_lexus_subgroups:
  path:         /lexus/{_locale}/articul/6/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{articul}/{token}
  defaults:     {_controller: CatalogLexusBundle:Articul:lexusArticulSubgroups, token: null}

articul_lexus_schemas:
  path:         /lexus/{_locale}/articul/7/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{articul}/{token}
  defaults:     {_controller: CatalogLexusBundle:Articul:lexusArticulSchemas, token: null}

articul_lexus_schema:
  path:         /lexus/{_locale}/articul/8/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{schemaCode}/{articul}/{token}
  defaults:     {_controller: CatalogLexusBundle:Articul:lexusArticulSchema, token: null}

articul_lexus_articuls:
  path:         /lexus/{_locale}/articul/9
  defaults:     {_controller: CatalogLexusBundle:Articul:articuls}
  requirements: {_method: POST}

articul_lexus_group:
  path:         /lexus/{_locale}/articul/8/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{subGroupCode}/{token}
  defaults:     {_controller: CatalogLexusBundle:Articul:getGroupBySubgroup, token: null}
catalog_lexus_homepage:
    path:     /hello/{name}
    defaults: { _controller: CatalogLexusBundle:Default:index }
