services:
#    catalog_lexus.example:
#        class: Catalog\LexusBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

  lexus_date_convertor.extension:
        class: Catalog\LexusBundle\Twig\Extension\DateConvertorExtension
        tags:
            - { name: twig.extension}
  lexus.catalog.model:
    class: Catalog\LexusBundle\Models\LexusCatalogModel
    calls:
       - [setRequestStack, ['@request_stack']]
    arguments:  ['@doctrine.dbal.lexus_connection']

  lexus.vin.model:
    class: Catalog\LexusBundle\Models\LexusVinModel
    calls:
       - [setRequestStack, ['@request_stack']]
    arguments:  ['@doctrine.dbal.lexus_connection']

  lexus.articul.model:
    class: Catalog\LexusBundle\Models\LexusArticulModel
    calls:
       - [setRequestStack, ['@request_stack']]
    arguments:  ['@doctrine.dbal.lexus_connection']


  my_form:
    class: Catalog\LexusBundle\Form\ComplectationType
