services:
#    catalog_cadillac.example:
#        class: Catalog\CadillacBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

  cadillac_date_convertor.extension:
        class: Catalog\CadillacBundle\Twig\Extension\DateConvertorExtension
        tags:
            - { name: twig.extension}
  cadillac.catalog.model:
    class: Catalog\CadillacBundle\Models\CadillacCatalogModel
    arguments:  ['@doctrine.dbal.cadillac_connection']

  cadillac.vin.model:
    class: Catalog\CadillacBundle\Models\CadillacVinModel
    arguments:  ['@doctrine.dbal.cadillac_connection']

  cadillac.articul.model:
    class: Catalog\CadillacBundle\Models\CadillacArticulModel
    arguments:  ['@doctrine.dbal.cadillac_connection']