catalog_bmw_enter:
  path:         /bmw/catalog/{token}
  defaults:     {_controller: CatalogBmwBundle:Catalog:bmwBilling}

catalog_bmw:
  path:         /bmw/catalog/0/{regionCode}/{token}
  defaults:     {_controller: CatalogBmwBundle:Catalog:regionsModels, regionCode: null}

catalog_bmw_modifications:
  path:         /bmw/catalog/1
  defaults:     {_controller: CatalogBmwBundle:Catalog:modifications}
  requirements: {_method: POST}

catalog_bmw_complectations:
  path:         /bmw/catalog/2/{regionCode}/{modelCode}/{modificationCode}
  defaults:     {_controller: CatalogBmwBundle:Catalog:complectations1}

catalog_bmw_complectation_korobka:
  path:         /bmw/catalog/12
  defaults:     {_controller: CatalogBmwBundle:Catalog:complectation_korobka}
  requirements: {_method: POST}

catalog_bmw_complectation_year:
  path:         /bmw/catalog/10
  defaults:     {_controller: CatalogBmwBundle:Catalog:complectation_year}
  requirements: {_method: POST}

catalog_bmw_complectation_month:
  path:         /bmw/catalog/11
  defaults:     {_controller: CatalogBmwBundle:Catalog:complectation_month}
  requirements: {_method: POST}

catalog_bmw_groups:
  path:         /bmw/catalog/3/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}
  defaults:     {_controller: CatalogBmwBundle:Catalog:groups}

catalog_bmw_subgroups:
  path:         /bmw/catalog/4/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}
  defaults:     {_controller: CatalogBmwBundle:Catalog:subgroups}

catalog_bmw_schemas:
  path:         /bmw/catalog/5/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}
  defaults:     {_controller: CatalogBmwBundle:Catalog:schemas}

catalog_bmw_schema:
  path:         /bmw/catalog/6/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{schemaCode}
  defaults:     {_controller: CatalogBmwBundle:Catalog:schema}

catalog_bmw_articuls:
  path:         /bmw/catalog/7
  defaults:     {_controller: CatalogBmwBundle:Catalog:articuls}
  requirements: {_method: POST}

catalog_bmw_group:
  path:         /bmw/catalog/8/{regionCode}/{modelCode}/{modificationCode}/{subGroupCode}
  defaults:     {_controller: CatalogBmwBundle:Catalog:getGroupBySubgroup}

#------------------------------------------------------------------------------

vin_bmw:
  path:         /bmw/vin/0
  defaults:     {_controller: CatalogBmwBundle:Vin:index}

vin_bmw_result:
  path:         /bmw/vin/1
  defaults:     {_controller: CatalogBmwBundle:Vin:result}
  requirements: {_method: POST}

vin_bmw_groups:
  path:         /bmw/vin/3/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}
  defaults:     {_controller: CatalogBmwBundle:Vin:groups}

vin_bmw_subgroups:
  path:         /bmw/vin/4/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}
  defaults:     {_controller: CatalogBmwBundle:Vin:subgroups}

vin_bmw_schemas:
  path:         /bmw/vin/5/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}
  defaults:     {_controller: CatalogBmwBundle:Vin:schemas}

vin_bmw_schema:
  path:         /bmw/vin/6/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{schemaCode}
  defaults:     {_controller: CatalogBmwBundle:Vin:schema}

vin_bmw_articuls:
  path:         /bmw/vin/7
  defaults:     {_controller: CatalogBmwBundle:Vin:articuls}
  requirements: {_method: POST}

vin_bmw_group:
  path:         /bmw/vin/8/{regionCode}/{modelCode}/{modificationCode}/{subGroupCode}
  defaults:     {_controller: CatalogBmwBundle:Vin:getGroupBySubgroup}

#---------------------------------------------------------------------------------------------

articul_bmw:
  path:         /bmw/articul/0
  defaults:     {_controller: CatalogBmwBundle:Articul:index}

articul_bmw_find:
  path:         /bmw/articul/1/{regionCode}
  defaults:     {_controller: CatalogBmwBundle:Articul:findByArticul, regionCode: null}

articul_bmw_modifications:
  path:         /bmw/articul/3
  defaults:     {_controller: CatalogBmwBundle:Articul:modifications}
  requirements: {_method: POST}

articul_bmw_complectations:
  path:         /bmw/articul/4/{regionCode}/{modelCode}/{modificationCode}
  defaults:     {_controller: CatalogBmwBundle:Articul:bmwArticulcomplectations1}

articul_bmw_complectation_korobka:
  path:         /bmw/articul/12
  defaults:     {_controller: CatalogBmwBundle:Articul:bmwArticulcomplectation_korobka}
  requirements: {_method: POST}

articul_bmw_complectation_year:
  path:         /bmw/articul/10
  defaults:     {_controller: CatalogBmwBundle:Articul:bmwArticulcomplectation_year}
  requirements: {_method: POST}

articul_bmw_complectation_month:
  path:         /bmw/articul/11
  defaults:     {_controller: CatalogBmwBundle:Articul:bmwArticulcomplectation_month}
  requirements: {_method: POST}


articul_bmw_groups:
  path:         /bmw/articul/5/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}
  defaults:     {_controller: CatalogBmwBundle:Articul:bmwArticulgroups}

articul_bmw_subgroups:
  path:         /bmw/articul/6/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}
  defaults:     {_controller: CatalogBmwBundle:Articul:bmwArticulSubgroups}

articul_bmw_schemas:
  path:         /bmw/articul/7/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}
  defaults:     {_controller: CatalogBmwBundle:Articul:bmwArticulSchemas}

articul_bmw_schema:
  path:         /bmw/articul/8/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{schemaCode}
  defaults:     {_controller: CatalogBmwBundle:Articul:bmwArticulSchema}

articul_bmw_articuls:
  path:         /bmw/articul/9
  defaults:     {_controller: CatalogBmwBundle:Articul:articuls}
  requirements: {_method: POST}

articul_bmw_group:
  path:         /bmw/articul/8/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{subGroupCode}
  defaults:     {_controller: CatalogBmwBundle:Articul:getGroupBySubgroup}
catalog_bmw_homepage:
    path:     /hello/{name}
    defaults: { _controller: CatalogBmwBundle:Default:index }
