catalog_bmw_token:
  path:         /bmw/catalog/0/{token}/{regionCode}
  defaults:     {_controller: CatalogBmwBundle:Catalog:regionsModels, token: null, regionCode: null}

catalog_bmw:
  path:         /bmw/{regionCode}
  defaults:     {_controller: CatalogBmwBundle:Catalog:regionsModels, regionCode: null}

catalog_bmw_modifications:
  path:         /bmw/catalog/1
  defaults:     {_controller: CatalogBmwBundle:Catalog:modifications}
  requirements: {_method: POST}

catalog_bmw_complectations:
  path:         /bmw/catalog/2/{regionCode}/{modelCode}/{modificationCode}/{token}
  defaults:     {_controller: CatalogBmwBundle:Catalog:complectations1, token: null}

catalog_bmw_complectation_korobka:
  path:         /bmw/catalog/12
  defaults:     {_controller: CatalogBmwBundle:Catalog:complectation_korobka}
  requirements: {_method: POST}

catalog_bmw_complectation_year:
  path:         /bmw/catalog/10
  defaults:     {_controller: CatalogBmwBundle:Catalog:complectation_year}
  requirements: {_method: POST}

catalog_bmw_complectation_month:
  path:         /bmw/catalog/11
  defaults:     {_controller: CatalogBmwBundle:Catalog:complectation_month}
  requirements: {_method: POST}

catalog_bmw_groups:
  path:         /bmw/catalog/3/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{token}
  defaults:     {_controller: CatalogBmwBundle:Catalog:groups, token: null}

catalog_bmw_subgroups:
  path:         /bmw/catalog/4/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{token}
  defaults:     {_controller: CatalogBmwBundle:Catalog:subgroups, token: null}

catalog_bmw_schemas:
  path:         /bmw/catalog/5/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{token}
  defaults:     {_controller: CatalogBmwBundle:Catalog:schemas, token: null}

catalog_bmw_schema:
  path:         /bmw/catalog/6/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{schemaCode}/{token}
  defaults:     {_controller: CatalogBmwBundle:Catalog:schema, token: null}

catalog_bmw_articuls:
  path:         /bmw/catalog/7
  defaults:     {_controller: CatalogBmwBundle:Catalog:articuls}
  requirements: {_method: POST}

catalog_bmw_group:
  path:         /bmw/catalog/8/{regionCode}/{modelCode}/{modificationCode}/{subGroupCode}/{token}
  defaults:     {_controller: CatalogBmwBundle:Catalog:getGroupBySubgroup}

#------------------------------------------------------------------------------

vin_bmw:
  path:         /bmw/vin/0/{token}
  defaults:     {_controller: CatalogBmwBundle:Vin:index, token: null}

vin_bmw_result:
  path:         /bmw/vin/1
  defaults:     {_controller: CatalogBmwBundle:Vin:result}
  requirements: {_method: POST}

vin_bmw_groups:
  path:         /bmw/vin/3/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{token}
  defaults:     {_controller: CatalogBmwBundle:Vin:groups, token: null}

vin_bmw_subgroups:
  path:         /bmw/vin/4/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{token}
  defaults:     {_controller: CatalogBmwBundle:Vin:subgroups, token: null}

vin_bmw_schemas:
  path:         /bmw/vin/5/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{token}
  defaults:     {_controller: CatalogBmwBundle:Vin:schemas, token: null}

vin_bmw_schema:
  path:         /bmw/vin/6/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{schemaCode}/{token}
  defaults:     {_controller: CatalogBmwBundle:Vin:schema, token: null}

vin_bmw_articuls:
  path:         /bmw/vin/7
  defaults:     {_controller: CatalogBmwBundle:Vin:articuls}
  requirements: {_method: POST}

vin_bmw_group:
  path:         /bmw/vin/8/{regionCode}/{modelCode}/{modificationCode}/{subGroupCode}/{token}
  defaults:     {_controller: CatalogBmwBundle:Vin:getGroupBySubgroup}

#---------------------------------------------------------------------------------------------

articul_bmw:
  path:         /bmw/articul/0/{token}
  defaults:     {_controller: CatalogBmwBundle:Articul:index, token: null}

articul_bmw_find_token:
  path:         /bmw/articul/1/{token}/{regionCode}
  defaults:     {_controller: CatalogBmwBundle:Articul:findByArticul, regionCode: null}

articul_bmw_find:
  path:         /bmw/articul/2/{regionCode}
  defaults:     {_controller: CatalogBmwBundle:Articul:findByArticul, regionCode: null}

articul_bmw_modifications:
  path:         /bmw/articul/3
  defaults:     {_controller: CatalogBmwBundle:Articul:modifications}
  requirements: {_method: POST}

articul_bmw_complectations:
  path:         /bmw/articul/4/{regionCode}/{modelCode}/{modificationCode}/{articul}/{token}
  defaults:     {_controller: CatalogBmwBundle:Articul:bmwArticulcomplectations1, token: null}

articul_bmw_complectation_korobka:
  path:         /bmw/articul/12
  defaults:     {_controller: CatalogBmwBundle:Articul:bmwArticulcomplectation_korobka}
  requirements: {_method: POST}

articul_bmw_complectation_year:
  path:         /bmw/articul/10
  defaults:     {_controller: CatalogBmwBundle:Articul:bmwArticulcomplectation_year}
  requirements: {_method: POST}

articul_bmw_complectation_month:
  path:         /bmw/articul/11
  defaults:     {_controller: CatalogBmwBundle:Articul:bmwArticulcomplectation_month}
  requirements: {_method: POST}

articul_bmw_groups:
  path:         /bmw/articul/5/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{articul}/{token}
  defaults:     {_controller: CatalogBmwBundle:Articul:bmwArticulgroups, token: null}

articul_bmw_subgroups:
  path:         /bmw/articul/6/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{articul}/{token}
  defaults:     {_controller: CatalogBmwBundle:Articul:bmwArticulSubgroups, token: null}

articul_bmw_schemas:
  path:         /bmw/articul/7/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{articul}/{token}
  defaults:     {_controller: CatalogBmwBundle:Articul:bmwArticulSchemas, token: null}

articul_bmw_schema:
  path:         /bmw/articul/8/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{schemaCode}/{articul}/{token}
  defaults:     {_controller: CatalogBmwBundle:Articul:bmwArticulSchema, token: null}

articul_bmw_articuls:
  path:         /bmw/articul/9
  defaults:     {_controller: CatalogBmwBundle:Articul:articuls}
  requirements: {_method: POST}

articul_bmw_group:
  path:         /bmw/articul/8/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{subGroupCode}/{token}
  defaults:     {_controller: CatalogBmwBundle:Articul:getGroupBySubgroup}




catalog_bmw_homepage:
    path:     /hello/{name}
    defaults: { _controller: CatalogBmwBundle:Default:index }
