catalog_mazda_token:
  path:         /mazda/catalog/0/{token}/{regionCode}
  defaults:     {_controller: CatalogMazdaBundle:Catalog:regionsModels, token: null, regionCode: null}

catalog_mazda:
  path:         /mazda/{regionCode}
  defaults:     {_controller: CatalogMazdaBundle:Catalog:regionsModels, regionCode: null}
  
catalog_mazda_modifications:
  path:         /mazda/catalog/1
  defaults:     {_controller: CatalogMazdaBundle:Catalog:modifications}
  requirements: {_method: POST}

catalog_mazda_complectations:
  path:         /mazda/catalog/2/{regionCode}/{modelCode}/{modificationCode}
  defaults:     {_controller: CatalogMazdaBundle:Catalog:complectations}

catalog_mazda_groups:
  path:         /mazda/catalog/3/{regionCode}/{modelCode}/{modificationCode}/{token}
  defaults:     {_controller: CatalogMazdaBundle:Catalog:groups, token: null}

catalog_mazda_subgroups:
  path:         /mazda/catalog/4/{regionCode}/{modelCode}/{modificationCode}/{groupCode}/{token}
  defaults:     {_controller: CatalogMazdaBundle:Catalog:subgroups, token: null}

catalog_mazda_schemas:
  path:         /mazda/catalog/5/{regionCode}/{modelCode}/{modificationCode}/{groupCode}/{subGroupCode}/{token}
  defaults:     {_controller: CatalogMazdaBundle:Catalog:schemas, token: null}

catalog_mazda_schema:
  path:         /mazda/catalog/6/{regionCode}/{modelCode}/{modificationCode}/{groupCode}/{subGroupCode}/{schemaCode}/{token}
  defaults:     {_controller: CatalogMazdaBundle:Catalog:schema, token: null}

catalog_mazda_articuls:
  path:         /mazda/catalog/7
  defaults:     {_controller: CatalogMazdaBundle:Catalog:articuls}
  requirements: {_method: POST}

catalog_mazda_group:
  path:         /mazda/catalog/8/{regionCode}/{modelCode}/{modificationCode}/{subGroupCode}/{token}
  defaults:     {_controller: CatalogMazdaBundle:Catalog:getGroupBySubgroup, token: null}

#------------------------------------------------------------------------------

vin_mazda:
  path:         /mazda/vin/0/{token}
  defaults:     {_controller: CatalogMazdaBundle:Vin:index, token: null}

vin_mazda_result:
  path:         /mazda/vin/1
  defaults:     {_controller: CatalogMazdaBundle:Vin:result}
  requirements: {_method: POST}

vin_mazda_groups:
  path:         /mazda/vin/3/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{token}
  defaults:     {_controller: CatalogMazdaBundle:Vin:vinGroups, token: nul}

vin_mazda_subgroups:
  path:         /mazda/vin/4/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{token}
  defaults:     {_controller: CatalogMazdaBundle:Vin:vinSubgroups, token: null}

vin_mazda_schemas:
  path:         /mazda/vin/5/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{token}
  defaults:     {_controller: CatalogMazdaBundle:Vin:vinSchemas, token: null}

vin_mazda_schema:
  path:         /mazda/vin/6/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{schemaCode}/{token}
  defaults:     {_controller: CatalogMazdaBundle:Vin:schema, token: null}

vin_mazda_articuls:
  path:         /mazda/vin/7
  defaults:     {_controller: CatalogMazdaBundle:Vin:articuls}
  requirements: {_method: POST}

vin_mazda_group:
  path:         /mazda/vin/8/{regionCode}/{modelCode}/{modificationCode}/{subGroupCode}/{token}
  defaults:     {_controller: CatalogMazdaBundle:Vin:getGroupBySubgroup, token: null}

#---------------------------------------------------------------------------------------------

articul_mazda:
  path:         /mazda/articul/0/{token}
  defaults:     {_controller: CatalogMazdaBundle:Articul:index, token: null}

articul_mazda_find_token:
  path:         /mazda/articul/1/{token}/{regionCode}
  defaults:     {_controller: CatalogMazdaBundle:Articul:findByArticul, token: null, regionCode: null}

articul_mazda_find:
  path:         /mazda/articul/2/{regionCode}
  defaults:     {_controller: CatalogMazdaBundle:Articul:findByArticul, regionCode: null}


#articul_mazda_regions:
#  path:         /mazda/articul/2/{regionCode}
#  defaults:     {_controller: CatalogMazdaBundle:Articul:regionsModels, regionCode: null}

articul_mazda_modifications:
  path:         /mazda/articul/3
  defaults:     {_controller: CatalogMazdaBundle:Articul:modifications}
  requirements: {_method: POST}

articul_mazda_complectations:
  path:         /mazda/articul/4/{regionCode}/{modelCode}/{modificationCode}
  defaults:     {_controller: CatalogMazdaBundle:Articul:complectations, token: null}

articul_mazda_groups:
  path:         /mazda/articul/5/{regionCode}/{modelCode}/{modificationCode}/{articul}/{token}
  defaults:     {_controller: CatalogMazdaBundle:Articul:mazdaArticulGroups, token: null}

articul_mazda_subgroups:
  path:         /mazda/articul/6/{regionCode}/{modelCode}/{modificationCode}/{groupCode}/{articul}/{token}
  defaults:     {_controller: CatalogMazdaBundle:Articul:mazdaArticulSubgroups, token: null}

articul_mazda_schemas:
  path:         /mazda/articul/7/{regionCode}/{modelCode}/{modificationCode}/{groupCode}/{subGroupCode}/{articul}/{token}
  defaults:     {_controller: CatalogMazdaBundle:Articul:mazdaArticulSchemas, token: null}

articul_mazda_schema:
  path:         /mazda/articul/8/{regionCode}/{modelCode}/{modificationCode}/{groupCode}/{subGroupCode}/{schemaCode}/{articul}/{token}
  defaults:     {_controller: CatalogMazdaBundle:Articul:mazdaArticulSchema, token: null}

articul_mazda_articuls:
  path:         /mazda/articul/9
  defaults:     {_controller: CatalogMazdaBundle:Articul:articuls}
  requirements: {_method: POST}

articul_mazda_group:
  path:         /mazda/articul/10/{regionCode}/{modelCode}/{modificationCode}/{subGroupCode}/{token}
  defaults:     {_controller: CatalogMazdaBundle:Articul:getGroupBySubgroup, token: null}