catalog_mazda:
  path:         /mazda/catalog/0/{regionCode}
  defaults:     {_controller: CatalogMazdaBundle:Catalog:regionsModels, regionCode: null}

catalog_mazda_modifications:
  path:         /mazda/catalog/1
  defaults:     {_controller: CatalogMazdaBundle:Catalog:modifications}
  requirements: {_method: POST}

catalog_mazda_complectations:
  path:         /mazda/catalog/2/{regionCode}/{modelCode}/{modificationCode}
  defaults:     {_controller: CatalogMazdaBundle:Catalog:complectations}

catalog_mazda_groups:
  path:         /mazda/catalog/3/{regionCode}/{modelCode}/{modificationCode}
  defaults:     {_controller: CatalogMazdaBundle:Catalog:groups}

catalog_mazda_subgroups:
  path:         /mazda/catalog/4/{regionCode}/{modelCode}/{modificationCode}/{groupCode}
  defaults:     {_controller: CatalogMazdaBundle:Catalog:subgroups}

catalog_mazda_schemas:
  path:         /mazda/catalog/5/{regionCode}/{modelCode}/{modificationCode}/{groupCode}/{subGroupCode}
  defaults:     {_controller: CatalogMazdaBundle:Catalog:schemas}

catalog_mazda_schema:
  path:         /mazda/catalog/6/{regionCode}/{modelCode}/{modificationCode}/{groupCode}/{subGroupCode}/{schemaCode}
  defaults:     {_controller: CatalogMazdaBundle:Catalog:schema}

catalog_mazda_articuls:
  path:         /mazda/catalog/7
  defaults:     {_controller: CatalogMazdaBundle:Catalog:articuls}
  requirements: {_method: POST}

catalog_mazda_group:
  path:         /mazda/catalog/8/{regionCode}/{modelCode}/{modificationCode}/{subGroupCode}
  defaults:     {_controller: CatalogMazdaBundle:Catalog:getGroupBySubgroup}

#------------------------------------------------------------------------------

vin_mazda:
  path:         /mazda/vin/0
  defaults:     {_controller: CatalogMazdaBundle:Vin:index}

vin_mazda_result:
  path:         /mazda/vin/1
  defaults:     {_controller: CatalogMazdaBundle:Vin:result}
  requirements: {_method: POST}

vin_mazda_groups:
  path:         /mazda/vin/3/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}
  defaults:     {_controller: CatalogMazdaBundle:Vin:vinGroups, complectationCode = null}

vin_mazda_subgroups:
  path:         /mazda/vin/4/{regionCode}/{modelCode}/{modificationCode}/{groupCode}
  defaults:     {_controller: CatalogMazdaBundle:Vin:subgroups}

vin_mazda_schemas:
  path:         /mazda/vin/5/{regionCode}/{modelCode}/{modificationCode}/{groupCode}/{subGroupCode}
  defaults:     {_controller: CatalogMazdaBundle:Vin:schemas}

vin_mazda_schema:
  path:         /mazda/vin/6/{regionCode}/{modelCode}/{modificationCode}/{groupCode}/{subGroupCode}/{schemaCode}
  defaults:     {_controller: CatalogMazdaBundle:Vin:schema}

vin_mazda_articuls:
  path:         /mazda/vin/7
  defaults:     {_controller: CatalogMazdaBundle:Vin:articuls}
  requirements: {_method: POST}

vin_mazda_group:
  path:         /mazda/vin/8/{regionCode}/{modelCode}/{modificationCode}/{subGroupCode}
  defaults:     {_controller: CatalogMazdaBundle:Vin:getGroupBySubgroup}

#---------------------------------------------------------------------------------------------

articul_mazda:
  path:         /mazda/articul/0
  defaults:     {_controller: CatalogMazdaBundle:Articul:index}

articul_mazda_find:
  path:         /mazda/articul/1
  defaults:     {_controller: CatalogMazdaBundle:Articul:findByArticul}

articul_mazda_regions:
  path:         /mazda/articul/2/{regionCode}
  defaults:     {_controller: CatalogMazdaBundle:Articul:regionsModels, regionCode: null}

articul_mazda_modifications:
  path:         /mazda/articul/3
  defaults:     {_controller: CatalogMazdaBundle:Articul:modifications}
  requirements: {_method: POST}

articul_mazda_complectations:
  path:         /mazda/articul/4/{regionCode}/{modelCode}/{modificationCode}
  defaults:     {_controller: CatalogMazdaBundle:Articul:complectations}

articul_mazda_groups:
  path:         /mazda/articul/5/{regionCode}/{modelCode}/{modificationCode}
  defaults:     {_controller: CatalogMazdaBundle:Articul:groups}

articul_mazda_subgroups:
  path:         /mazda/articul/6/{regionCode}/{modelCode}/{modificationCode}/{groupCode}
  defaults:     {_controller: CatalogMazdaBundle:Articul:subgroups}

articul_mazda_schemas:
  path:         /mazda/articul/7/{regionCode}/{modelCode}/{modificationCode}/{groupCode}/{subGroupCode}
  defaults:     {_controller: CatalogMazdaBundle:Articul:schemas}

articul_mazda_schema:
  path:         /mazda/articul/8/{regionCode}/{modelCode}/{modificationCode}/{groupCode}/{subGroupCode}/{schemaCode}
  defaults:     {_controller: CatalogMazdaBundle:Articul:schema}

articul_mazda_articuls:
  path:         /mazda/articul/9
  defaults:     {_controller: CatalogMazdaBundle:Articul:articuls}
  requirements: {_method: POST}

articul_mazda_group:
  path:         /mazda/articul/10/{regionCode}/{modelCode}/{modificationCode}/{subGroupCode}
  defaults:     {_controller: CatalogMazdaBundle:Articul:getGroupBySubgroup}