catalog_mazda:
  path:         /mazda/catalog/{regionCode}
  defaults:     {_controller: CatalogMazdaBundle:Catalog:regionsModels, regionCode: null}

catalog_mazda_modifications:
  path:         /mazda/modifications
  defaults:     {_controller: CatalogMazdaBundle:Catalog:modifications}
  requirements: {_method: POST}