services:
#    catalog_mazda.example:
#        class: Catalog\MazdaBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

  mazda.catalog.model:
    class: Catalog\MazdaBundle\Models\MazdaCatalogModel
    arguments:  ['@doctrine.dbal.mazda_connection']

  mazda.vin.model:
    class: Catalog\MazdaBundle\Models\MazdaVinModel
    arguments:  ['@doctrine.dbal.mazda_connection']

  mazda.articul.model:
    class: Catalog\MazdaBundle\Models\MazdaArticulModel
    arguments:  ['@doctrine.dbal.mazda_connection']