services:
     my_token_info:
         class: Acme\BillingBundle\Services\TokenData
#    acme_billing.example:
#        class: Acme\BillingBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

