catalog_nissan_token:
  path:         /nissan/catalog/0/{token}/{regionCode}
  defaults:     {_controller: CatalogNissanBundle:Catalog:regionsModels, token: null, regionCode: null}

catalog_nissan:
  path:         /nissan/{regionCode}
  defaults:     {_controller: CatalogNissanBundle:Catalog:regionsModels, regionCode: null}

catalog_nissan_modifications:
  path:         /nissan/catalog/1
  defaults:     {_controller: CatalogNissanBundle:Catalog:modifications}
  requirements: {_method: POST}

catalog_nissan_complectations:
  path:         /nissan/catalog/2/{regionCode}/{modelCode}/{modificationCode}/{token}
  defaults:     {_controller: CatalogNissanBundle:Catalog:complectations, token: null}

catalog_nissan_groups:
  path:         /nissan/catalog/3/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{token}
  defaults:     {_controller: CatalogNissanBundle:Catalog:groups, token: null}

catalog_nissan_subgroups:
  path:         /nissan/catalog/4/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{token}
  defaults:     {_controller: CatalogNissanBundle:Catalog:subgroups, token: null}

catalog_nissan_schemas:
  path:         /nissan/catalog/5/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{token}
  defaults:     {_controller: CatalogNissanBundle:Catalog:schemas, token: null}

catalog_nissan_schema:
  path:         /nissan/catalog/6/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{schemaCode}/{token}
  defaults:     {_controller: CatalogNissanBundle:Catalog:schema, token: null}

catalog_nissan_articuls:
  path:         /nissan/catalog/7
  defaults:     {_controller: CatalogNissanBundle:Catalog:articuls}
  requirements: {_method: POST}

catalog_nissan_group:
  path:         /nissan/catalog/8/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{subGroupCode}/{token}
  defaults:     {_controller: CatalogNissanBundle:Catalog:getGroupBySubgroup}

#------------------------------------------------------------------------------

vin_nissan:
  path:         /nissan/vin/0/{token}
  defaults:     {_controller: CatalogNissanBundle:Vin:index, token: null}

vin_nissan_result:
  path:         /nissan/vin/1
  defaults:     {_controller: CatalogNissanBundle:Vin:result}
  requirements: {_method: POST}

vin_nissan_groups:
  path:         /nissan/vin/3/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{token}
  defaults:     {_controller: CatalogNissanBundle:Vin:groups, token: null}

vin_nissan_subgroups:
  path:         /nissan/vin/4/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{token}
  defaults:     {_controller: CatalogNissanBundle:Vin:subgroups, token: null}

vin_nissan_schemas:
  path:         /nissan/vin/5/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{token}
  defaults:     {_controller: CatalogNissanBundle:Vin:schemas, token: null}

vin_nissan_schema:
  path:         /nissan/vin/6/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{schemaCode}/{token}
  defaults:     {_controller: CatalogNissanBundle:Vin:schema, token: null}

vin_nissan_articuls:
  path:         /nissan/vin/7
  defaults:     {_controller: CatalogNissanBundle:Vin:articuls}
  requirements: {_method: POST}

vin_nissan_group:
  path:         /nissan/vin/8/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{subGroupCode}/{token}
  defaults:     {_controller: CatalogNissanBundle:Vin:getGroupBySubgroup}

#---------------------------------------------------------------------------------------------

articul_nissan:
  path:         /nissan/articul/0/{token}
  defaults:     {_controller: CatalogNissanBundle:Articul:index, token: null}

articul_nissan_find_token:
  path:         /nissan/articul/1/{token}/{regionCode}
  defaults:     {_controller: CatalogNissanBundle:Articul:findByArticul, regionCode: null}

articul_nissan_find:
  path:         /nissan/articul/2/{regionCode}
  defaults:     {_controller: CatalogNissanBundle:Articul:findByArticul, regionCode: null}

articul_nissan_modifications:
  path:         /nissan/articul/3
  defaults:     {_controller: CatalogNissanBundle:Articul:modifications}
  requirements: {_method: POST}

articul_nissan_complectations:
  path:         /nissan/articul/4/{regionCode}/{modelCode}/{modificationCode}/{articul}/{token}
  defaults:     {_controller: CatalogNissanBundle:Articul:nissanArticulComplectations, token: null}

articul_nissan_groups:
  path:         /nissan/articul/5/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{articul}/{token}
  defaults:     {_controller: CatalogNissanBundle:Articul:nissanArticulgroups, token: null}

articul_nissan_subgroups:
  path:         /nissan/articul/6/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{articul}/{token}
  defaults:     {_controller: CatalogNissanBundle:Articul:nissanArticulSubgroups, token: null}

articul_nissan_schemas:
  path:         /nissan/articul/7/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{articul}/{token}
  defaults:     {_controller: CatalogNissanBundle:Articul:nissanArticulSchemas, token: null}

articul_nissan_schema:
  path:         /nissan/articul/8/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{schemaCode}/{articul}/{token}
  defaults:     {_controller: CatalogNissanBundle:Articul:nissanArticulSchema, token: null}

articul_nissan_articuls:
  path:         /nissan/articul/9
  defaults:     {_controller: CatalogNissanBundle:Articul:articuls}
  requirements: {_method: POST}

articul_nissan_group:
  path:         /nissan/articul/8/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{subGroupCode}/{token}
  defaults:     {_controller: CatalogNissanBundle:Articul:getGroupBySubgroup}


catalog_nissan_homepage:
    path:     /hello/{name}
    defaults: { _controller: CatalogNissanBundle:Default:index }
