catalog_fiatprofessional_token:
  path:         /fiatprofessional/catalog/0/{token}/{regionCode}
  defaults:     {_controller: CatalogFiatProfessionalBundle:Catalog:regionsModels, token: null, regionCode: null}

catalog_fiatprofessional:
  path:         /fiatprofessional/{regionCode}
  defaults:     {_controller: CatalogFiatProfessionalBundle:Catalog:regionsModels, regionCode: null}

catalog_fiatprofessional_modifications:
  path:         /fiatprofessional/catalog/1
  defaults:     {_controller: CatalogFiatProfessionalBundle:Catalog:modifications}
  requirements: {_method: POST}

catalog_fiatprofessional_complectations:
  path:         /fiatprofessional/catalog/2/{regionCode}/{modelCode}/{modificationCode}/{token}
  defaults:     {_controller: CatalogFiatProfessionalBundle:Catalog:complectations, token: null}

catalog_fiatprofessional_groups:
  path:         /fiatprofessional/catalog/3/{regionCode}/{modelCode}/{modificationCode}/{token}
  defaults:     {_controller: CatalogFiatProfessionalBundle:Catalog:groups, token: null}

catalog_fiatprofessional_subgroups:
  path:         /fiatprofessional/catalog/4/{regionCode}/{modelCode}/{modificationCode}/{groupCode}/{token}
  defaults:     {_controller: CatalogFiatProfessionalBundle:Catalog:subgroups, token: null}

catalog_fiatprofessional_schemas:
  path:         /fiatprofessional/catalog/5/{regionCode}/{modelCode}/{modificationCode}/{groupCode}/{subGroupCode}/{token}
  defaults:     {_controller: CatalogFiatProfessionalBundle:Catalog:schemas, token: null}

catalog_fiatprofessional_schema:
  path:         /fiatprofessional/catalog/6/{regionCode}/{modelCode}/{modificationCode}/{groupCode}/{subGroupCode}/{schemaCode}/{token}
  defaults:     {_controller: CatalogFiatProfessionalBundle:Catalog:schema, token: null}

catalog_fiatprofessional_articuls:
  path:         /fiatprofessional/catalog/7
  defaults:     {_controller: CatalogFiatProfessionalBundle:Catalog:articuls}
  requirements: {_method: POST}

catalog_fiatprofessional_group:
  path:         /fiatprofessional/catalog/8/{regionCode}/{modelCode}/{modificationCode}/{subGroupCode}/{token}
  defaults:     {_controller: CatalogFiatProfessionalBundle:Catalog:getGroupBySubgroup}

#------------------------------------------------------------------------------

vin_fiatprofessional:
  path:         /fiatprofessional/vin/0/{token}
  defaults:     {_controller: CatalogFiatProfessionalBundle:Vin:index, token: null}

vin_fiatprofessional_result:
  path:         /fiatprofessional/vin/1
  defaults:     {_controller: CatalogFiatProfessionalBundle:Vin:result}
  requirements: {_method: POST}

vin_fiatprofessional_groups:
  path:         /fiatprofessional/vin/3/{regionCode}/{modelCode}/{modificationCode}/{token}
  defaults:     {_controller: CatalogFiatProfessionalBundle:Vin:groups, token: null}

vin_fiatprofessional_subgroups:
  path:         /fiatprofessional/vin/4/{regionCode}/{modelCode}/{modificationCode}/{groupCode}/{token}
  defaults:     {_controller: CatalogFiatProfessionalBundle:Vin:subgroups, token: null}

vin_fiatprofessional_schemas:
  path:         /fiatprofessional/vin/5/{regionCode}/{modelCode}/{modificationCode}/{groupCode}/{subGroupCode}/{token}
  defaults:     {_controller: CatalogFiatProfessionalBundle:Vin:schemas, token: null}

vin_fiatprofessional_schema:
  path:         /fiatprofessional/vin/6/{regionCode}/{modelCode}/{modificationCode}/{groupCode}/{subGroupCode}/{schemaCode}/{token}
  defaults:     {_controller: CatalogFiatProfessionalBundle:Vin:schema, token: null}

vin_fiatprofessional_articuls:
  path:         /fiatprofessional/vin/7
  defaults:     {_controller: CatalogFiatProfessionalBundle:Vin:vinarticuls}
  requirements: {_method: POST}

vin_fiatprofessional_group:
  path:         /fiatprofessional/vin/8/{regionCode}/{modelCode}/{modificationCode}/{subGroupCode}/{token}
  defaults:     {_controller: CatalogFiatProfessionalBundle:Vin:getGroupBySubgroup}

#---------------------------------------------------------------------------------------------

articul_fiatprofessional:
  path:         /fiatprofessional/articul/0/{token}
  defaults:     {_controller: CatalogFiatProfessionalBundle:Articul:index, token: null}

articul_fiatprofessional_find_token:
  path:         /fiatprofessional/articul/1/{token}/{regionCode}
  defaults:     {_controller: CatalogFiatProfessionalBundle:Articul:findByArticul, regionCode: null}

articul_fiatprofessional_find:
  path:         /fiatprofessional/articul/2/{regionCode}
  defaults:     {_controller: CatalogFiatProfessionalBundle:Articul:findByArticul, regionCode: null}

articul_fiatprofessional_modifications:
  path:         /fiatprofessional/articul/3
  defaults:     {_controller: CatalogFiatProfessionalBundle:Articul:modifications}
  requirements: {_method: POST}

articul_fiatprofessional_complectations:
  path:         /fiatprofessional/articul/4/{regionCode}/{modelCode}/{modificationCode}/{articul}/{token}
  defaults:     {_controller: CatalogFiatProfessionalBundle:Articul:fiatprofessionalArticulComplectations, token: null}

articul_fiatprofessional_groups:
  path:         /fiatprofessional/articul/5/{regionCode}/{modelCode}/{modificationCode}/{articul}/{token}
  defaults:     {_controller: CatalogFiatProfessionalBundle:Articul:fiatprofessionalArticulgroups, token: null}

articul_fiatprofessional_subgroups:
  path:         /fiatprofessional/articul/6/{regionCode}/{modelCode}/{modificationCode}/{groupCode}/{articul}/{token}
  defaults:     {_controller: CatalogFiatProfessionalBundle:Articul:fiatprofessionalArticulSubgroups, token: null}

articul_fiatprofessional_schemas:
  path:         /fiatprofessional/articul/7/{regionCode}/{modelCode}/{modificationCode}/{groupCode}/{subGroupCode}/{articul}/{token}
  defaults:     {_controller: CatalogFiatProfessionalBundle:Articul:fiatprofessionalArticulSchemas, token: null}

articul_fiatprofessional_schema:
  path:         /fiatprofessional/articul/8/{regionCode}/{modelCode}/{modificationCode}/{groupCode}/{subGroupCode}/{schemaCode}/{articul}/{token}
  defaults:     {_controller: CatalogFiatProfessionalBundle:Articul:fiatprofessionalArticulSchema, token: null}

articul_fiatprofessional_articuls:
  path:         /fiatprofessional/articul/9
  defaults:     {_controller: CatalogFiatProfessionalBundle:Articul:fiatprofessionalArticularticuls}
  requirements: {_method: POST}

articul_fiatprofessional_group:
  path:         /fiatprofessional/articul/8/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{subGroupCode}/{token}
  defaults:     {_controller: CatalogFiatProfessionalBundle:Articul:getGroupBySubgroup}
catalog_fiatprofessional_homepage:
    path:     /hello/{name}
    defaults: { _controller: CatalogFiatProfessionalBundle:Default:index }
