services:
#    catalog_mitsubishi.example:
#        class: Catalog\MitsubishiBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

  mitsubishi_date_convertor.extension:
        class: Catalog\MitsubishiBundle\Twig\Extension\DateConvertorExtension
        tags:
            - { name: twig.extension}
  mitsubishi.catalog.model:
    class: Catalog\MitsubishiBundle\Models\MitsubishiCatalogModel
    arguments:  ['@doctrine.dbal.mitsubishi_connection']

  mitsubishi.vin.model:
    class: Catalog\MitsubishiBundle\Models\MitsubishiVinModel
    arguments:  ['@doctrine.dbal.mitsubishi_connection']

  mitsubishi.articul.model:
    class: Catalog\MitsubishiBundle\Models\MitsubishiArticulModel
    arguments:  ['@doctrine.dbal.mitsubishi_connection']