catalog_hyundai_form:
  path:         /hyundai/catalog/form
  defaults:     {_controller: CatalogHyundaiBundle:Catalog:form}
  requirements: {_method: POST}

catalog_hyundai_token:
  path:         /hyundai/catalog/0/{token}/{_locale}/{regionCode}
  defaults:     {_controller: CatalogHyundaiBundle:Catalog:regionsModels, _locale: ru, token: null, regionCode: null}

catalog_hyundai:
  path:         /hyundai/{_locale}/{regionCode}
  defaults:     {_controller: CatalogHyundaiBundle:Catalog:regionsModels, _locale: ru, regionCode: null}

catalog_hyundai_modifications:
  path:         /hyundai/{_locale}/catalog/1
  defaults:     {_controller: CatalogHyundaiBundle:Catalog:modifications}
  requirements: {_method: POST}

catalog_hyundai_complectations:
  path:         /hyundai/{_locale}/catalog/2/{regionCode}/{modelCode}/{modificationCode}/{token}
  defaults:     {_controller: CatalogHyundaiBundle:Catalog:complectations, token: null}

catalog_hyundai_complectation_form_valid_value:
  path:         /hyundai/{_locale}/catalog/12
  defaults:     {_controller: CatalogHyundaiBundle:Catalog:complectationFormValidValue}
  requirements: {_method: POST}

catalog_hyundai_groups:
  path:         /hyundai/{_locale}/catalog/3/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{token}
  defaults:     {_controller: CatalogHyundaiBundle:Catalog:groups, token: null}

catalog_hyundai_subgroups:
  path:         /hyundai/{_locale}/catalog/4/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{token}
  defaults:     {_controller: CatalogHyundaiBundle:Catalog:subgroups, token: null}

catalog_hyundai_schemas:
  path:         /hyundai/{_locale}/catalog/5/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{token}
  defaults:     {_controller: CatalogHyundaiBundle:Catalog:schemas, token: null}

catalog_hyundai_schema:
  path:         /hyundai/{_locale}/catalog/6/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{schemaCode}/{token}
  defaults:     {_controller: CatalogHyundaiBundle:Catalog:schema, token: null}

catalog_hyundai_articuls:
  path:         /hyundai/{_locale}/catalog/7
  defaults:     {_controller: CatalogHyundaiBundle:Catalog:articuls}
  requirements: {_method: POST}

catalog_hyundai_group:
  path:         /hyundai/{_locale}/catalog/8/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{subGroupCode}/{token}
  defaults:     {_controller: CatalogHyundaiBundle:Catalog:getGroupBySubgroup, token: null}

#------------------------------------------------------------------------------

vin_hyundai:
  path:         /hyundai/{_locale}/vin/0/{token}
  defaults:     {_controller: CatalogHyundaiBundle:Vin:index, token: null}

vin_hyundai_result:
  path:         /hyundai/{_locale}/vin/1
  defaults:     {_controller: CatalogHyundaiBundle:Vin:result}
  requirements: {_method: POST}

vin_hyundai_groups:
  path:         /hyundai/{_locale}/vin/3/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{token}
  defaults:     {_controller: CatalogHyundaiBundle:Vin:groups, token: null}

vin_hyundai_subgroups:
  path:         /hyundai/{_locale}/vin/4/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{token}
  defaults:     {_controller: CatalogHyundaiBundle:Vin:subgroups, token: null}

vin_hyundai_schemas:
  path:         /hyundai/{_locale}/vin/5/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{token}
  defaults:     {_controller: CatalogHyundaiBundle:Vin:schemas, token: null}

vin_hyundai_schema:
  path:         /hyundai/{_locale}/vin/6/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{schemaCode}/{token}
  defaults:     {_controller: CatalogHyundaiBundle:Vin:schema, token: null}

vin_hyundai_articuls:
  path:         /hyundai/{_locale}/vin/7
  defaults:     {_controller: CatalogHyundaiBundle:Vin:articuls}
  requirements: {_method: POST}

vin_hyundai_group:
  path:         /hyundai/{_locale}/vin/8/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{subGroupCode}/{token}
  defaults:     {_controller: CatalogHyundaiBundle:Vin:getGroupBySubgroup, token: null}

#---------------------------------------------------------------------------------------------

articul_hyundai:
  path:         /hyundai/{_locale}/articul/0/{token}
  defaults:     {_controller: CatalogHyundaiBundle:Articul:index, token: null}

articul_hyundai_find_token:
  path:         /hyundai/{_locale}/articul/1/{token}/{regionCode}
  defaults:     {_controller: CatalogHyundaiBundle:Articul:findByArticul, regionCode: null}

articul_hyundai_find:
  path:         /hyundai/{_locale}/articul/2/{regionCode}
  defaults:     {_controller: CatalogHyundaiBundle:Articul:findByArticul, regionCode: null}

articul_hyundai_modifications:
  path:         /hyundai/{_locale}/articul/3
  defaults:     {_controller: CatalogHyundaiBundle:Articul:modifications}
  requirements: {_method: POST}

articul_hyundai_complectations:
  path:         /hyundai/{_locale}/articul/4/{regionCode}/{modelCode}/{modificationCode}/{articul}/{token}
  defaults:     {_controller: CatalogHyundaiBundle:Articul:hyundaiArticulComplectations, token: null}

articul_hyundai_groups:
  path:         /hyundai/{_locale}/articul/5/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{articul}/{token}
  defaults:     {_controller: CatalogHyundaiBundle:Articul:hyundaiArticulgroups, token: null}

articul_hyundai_subgroups:
  path:         /hyundai/{_locale}/articul/6/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{articul}/{token}
  defaults:     {_controller: CatalogHyundaiBundle:Articul:hyundaiArticulSubgroups, token: null}

articul_hyundai_schemas:
  path:         /hyundai/{_locale}/articul/7/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{articul}/{token}
  defaults:     {_controller: CatalogHyundaiBundle:Articul:hyundaiArticulSchemas, token: null}

articul_hyundai_schema:
  path:         /hyundai/{_locale}/articul/8/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{schemaCode}/{articul}/{token}
  defaults:     {_controller: CatalogHyundaiBundle:Articul:hyundaiArticulSchema, token: null}

articul_hyundai_articuls:
  path:         /hyundai/{_locale}/articul/9
  defaults:     {_controller: CatalogHyundaiBundle:Articul:articuls}
  requirements: {_method: POST}

articul_hyundai_group:
  path:         /hyundai/{_locale}/articul/8/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{subGroupCode}/{token}
  defaults:     {_controller: CatalogHyundaiBundle:Articul:getGroupBySubgroup, token: null}

catalog_hyundai_homepage:
    path:     /hello/{name}
    defaults: { _controller: CatalogHyundaiBundle:Default:index }
