services:
#    catalog_hyundai.example:
#        class: Catalog\HyundaiBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

  hyundai_date_convertor.extension:
        class: Catalog\HyundaiBundle\Twig\Extension\DateConvertorExtension
        tags:
            - { name: twig.extension}
  hyundai.catalog.model:
    class: Catalog\HyundaiBundle\Models\HyundaiCatalogModel
    arguments:  ['@doctrine.dbal.hyundai_connection']

  hyundai.vin.model:
    class: Catalog\HyundaiBundle\Models\HyundaiVinModel
    arguments:  ['@doctrine.dbal.hyundai_connection']

  hyundai.articul.model:
    class: Catalog\HyundaiBundle\Models\HyundaiArticulModel
    arguments:  ['@doctrine.dbal.hyundai_connection']