catalog_bmv:
  path:         /bmv/catalog/0/{regionCode}
  defaults:     {_controller: CatalogBmvBundle:Catalog:regionsModels, regionCode: null}

catalog_bmv_modifications:
  path:         /bmv/catalog/1
  defaults:     {_controller: CatalogBmvBundle:Catalog:modifications}
  requirements: {_method: POST}

catalog_bmv_complectations:
  path:         /bmv/catalog/2/{regionCode}/{modelCode}/{modificationCode}
  defaults:     {_controller: CatalogBmvBundle:Catalog:complectations}

catalog_bmv_groups:
  path:         /bmv/catalog/3/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}
  defaults:     {_controller: CatalogBmvBundle:Catalog:groups}

catalog_bmv_subgroups:
  path:         /bmv/catalog/4/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}
  defaults:     {_controller: CatalogBmvBundle:Catalog:subgroups}

catalog_bmv_schemas:
  path:         /bmv/catalog/5/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}
  defaults:     {_controller: CatalogBmvBundle:Catalog:schemas}

catalog_bmv_schema:
  path:         /bmv/catalog/6/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{schemaCode}
  defaults:     {_controller: CatalogBmvBundle:Catalog:schema}

catalog_bmv_articuls:
  path:         /bmv/catalog/7
  defaults:     {_controller: CatalogBmvBundle:Catalog:articuls}
  requirements: {_method: POST}

catalog_bmv_group:
  path:         /bmv/catalog/8/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{subGroupCode}
  defaults:     {_controller: CatalogBmvBundle:Catalog:getGroupBySubgroup}

#------------------------------------------------------------------------------

vin_bmv:
  path:         /bmv/vin/0
  defaults:     {_controller: CatalogBmvBundle:Vin:index}

vin_bmv_result:
  path:         /bmv/vin/1
  defaults:     {_controller: CatalogBmvBundle:Vin:result}
  requirements: {_method: POST}

vin_bmv_groups:
  path:         /bmv/vin/3/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}
  defaults:     {_controller: CatalogBmvBundle:Vin:groups}

vin_bmv_subgroups:
  path:         /bmv/vin/4/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}
  defaults:     {_controller: CatalogBmvBundle:Vin:vinSubgroups}

vin_bmv_schemas:
  path:         /bmv/vin/5/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}
  defaults:     {_controller: CatalogBmvBundle:Vin:schemas}

vin_bmv_schema:
  path:         /bmv/vin/6/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{schemaCode}
  defaults:     {_controller: CatalogBmvBundle:Vin:schema}

vin_bmv_articuls:
  path:         /bmv/vin/7
  defaults:     {_controller: CatalogBmvBundle:Vin:articuls}
  requirements: {_method: POST}

vin_bmv_group:
  path:         /bmv/vin/8/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{subGroupCode}
  defaults:     {_controller: CatalogBmvBundle:Vin:getGroupBySubgroup}

#---------------------------------------------------------------------------------------------

articul_bmv:
  path:         /bmv/articul/0
  defaults:     {_controller: CatalogBmvBundle:Articul:index}

articul_bmv_find:
  path:         /bmv/articul/1/{regionCode}
  defaults:     {_controller: CatalogBmvBundle:Articul:findByArticul, regionCode: null}

articul_bmv_modifications:
  path:         /bmv/articul/3
  defaults:     {_controller: CatalogBmvBundle:Articul:modifications}
  requirements: {_method: POST}

articul_bmv_complectations:
  path:         /bmv/articul/4/{regionCode}/{modelCode}/{modificationCode}
  defaults:     {_controller: CatalogBmvBundle:Articul:bmvArticulComplectations}

articul_bmv_groups:
  path:         /bmv/articul/5/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}
  defaults:     {_controller: CatalogBmvBundle:Articul:bmvArticulgroups}

articul_bmv_subgroups:
  path:         /bmv/articul/6/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}
  defaults:     {_controller: CatalogBmvBundle:Articul:bmvArticulSubgroups}

articul_bmv_schemas:
  path:         /bmv/articul/7/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}
  defaults:     {_controller: CatalogBmvBundle:Articul:bmvArticulSchemas}

articul_bmv_schema:
  path:         /bmv/articul/8/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{schemaCode}
  defaults:     {_controller: CatalogBmvBundle:Articul:bmvArticulSchema}

articul_bmv_articuls:
  path:         /bmv/articul/9
  defaults:     {_controller: CatalogBmvBundle:Articul:articuls}
  requirements: {_method: POST}

articul_bmv_group:
  path:         /bmv/articul/8/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{subGroupCode}
  defaults:     {_controller: CatalogBmvBundle:Articul:getGroupBySubgroup}
catalog_bmv_homepage:
    path:     /hello/{name}
    defaults: { _controller: CatalogBmvBundle:Default:index }
