catalog_kia_token:
  path:         /kia/catalog/0/{token}/{_locale}/{regionCode}
  defaults:     {_controller: CatalogKiaBundle:Catalog:regionsModels, _locale: ru, token: null, regionCode: null}

catalog_kia:
  path:         /kia/{_locale}/{regionCode}
  defaults:     {_controller: CatalogKiaBundle:Catalog:regionsModels, _locale: ru, regionCode: null}

catalog_kia_modifications:
  path:         /kia/{_locale}/catalog/1
  defaults:     {_controller: CatalogKiaBundle:Catalog:modifications}
  requirements: {_method: POST}

catalog_kia_complectations:
  path:         /kia/{_locale}/catalog/2/{regionCode}/{modelCode}/{modificationCode}/{token}
  defaults:     {_controller: CatalogKiaBundle:Catalog:complectations, token: null}

catalog_kia_groups:
  path:         /kia/{_locale}/catalog/3/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{token}
  defaults:     {_controller: CatalogKiaBundle:Catalog:groups, token: null}

catalog_kia_subgroups:
  path:         /kia/{_locale}/catalog/4/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{token}
  defaults:     {_controller: CatalogKiaBundle:Catalog:subgroups, token: null}

catalog_kia_schemas:
  path:         /kia/{_locale}/catalog/5/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{token}
  defaults:     {_controller: CatalogKiaBundle:Catalog:schemas, token: null}

catalog_kia_schema:
  path:         /kia/{_locale}/catalog/6/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{schemaCode}/{token}
  defaults:     {_controller: CatalogKiaBundle:Catalog:schema, token: null}

catalog_kia_articuls:
  path:         /kia/{_locale}/catalog/7
  defaults:     {_controller: CatalogKiaBundle:Catalog:articuls}
  requirements: {_method: POST}

catalog_kia_group:
  path:         /kia/{_locale}/catalog/8/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{subGroupCode}/{token}
  defaults:     {_controller: CatalogKiaBundle:Catalog:getGroupBySubgroup, token: null}

#------------------------------------------------------------------------------

vin_kia:
  path:         /kia/{_locale}/vin/0/{token}
  defaults:     {_controller: CatalogKiaBundle:Vin:index, token: null}

vin_kia_result:
  path:         /kia/{_locale}/vin/1
  defaults:     {_controller: CatalogKiaBundle:Vin:result}
  requirements: {_method: POST}

vin_kia_groups:
  path:         /kia/{_locale}/vin/3/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{token}
  defaults:     {_controller: CatalogKiaBundle:Vin:groups, token: null}

vin_kia_subgroups:
  path:         /kia/{_locale}/vin/4/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{token}
  defaults:     {_controller: CatalogKiaBundle:Vin:vinSubgroups, token: null}

vin_kia_schemas:
  path:         /kia/{_locale}/vin/5/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{token}
  defaults:     {_controller: CatalogKiaBundle:Vin:schemas, token: null}

vin_kia_schema:
  path:         /kia/{_locale}/vin/6/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{schemaCode}/{token}
  defaults:     {_controller: CatalogKiaBundle:Vin:schema, token: null}

vin_kia_articuls:
  path:         /kia/{_locale}/vin/7
  defaults:     {_controller: CatalogKiaBundle:Vin:articuls}
  requirements: {_method: POST}

vin_kia_group:
  path:         /kia/{_locale}/vin/8/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{subGroupCode}/{token}
  defaults:     {_controller: CatalogKiaBundle:Vin:getGroupBySubgroup, token: null}

#---------------------------------------------------------------------------------------------

articul_kia:
  path:         /kia/{_locale}/articul/0/{token}
  defaults:     {_controller: CatalogKiaBundle:Articul:index, token: null}

articul_kia_find_token:
  path:         /kia/{_locale}/articul/1/{token}/{regionCode}
  defaults:     {_controller: CatalogKiaBundle:Articul:findByArticul, regionCode: null}

articul_kia_find:
  path:         /kia/{_locale}/articul/2/{regionCode}
  defaults:     {_controller: CatalogKiaBundle:Articul:findByArticul, regionCode: null}

articul_kia_modifications:
  path:         /kia/{_locale}/articul/3
  defaults:     {_controller: CatalogKiaBundle:Articul:modifications}
  requirements: {_method: POST}

articul_kia_complectations:
  path:         /kia/{_locale}/articul/4/{regionCode}/{modelCode}/{modificationCode}/{articul}/{token}
  defaults:     {_controller: CatalogKiaBundle:Articul:kiaArticulComplectations, token: null}

articul_kia_groups:
  path:         /kia/{_locale}/articul/5/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{articul}/{token}
  defaults:     {_controller: CatalogKiaBundle:Articul:kiaArticulgroups, token: null}

articul_kia_subgroups:
  path:         /kia/{_locale}/articul/6/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{articul}/{token}
  defaults:     {_controller: CatalogKiaBundle:Articul:kiaArticulSubgroups, token: null}

articul_kia_schemas:
  path:         /kia/{_locale}/articul/7/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{articul}/{token}
  defaults:     {_controller: CatalogKiaBundle:Articul:kiaArticulSchemas, token: null}

articul_kia_schema:
  path:         /kia/{_locale}/articul/8/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{groupCode}/{subGroupCode}/{schemaCode}/{articul}/{token}
  defaults:     {_controller: CatalogKiaBundle:Articul:kiaArticulSchema, token: null}

articul_kia_articuls:
  path:         /kia/{_locale}/articul/9
  defaults:     {_controller: CatalogKiaBundle:Articul:articuls}
  requirements: {_method: POST}

articul_kia_group:
  path:         /kia/{_locale}/articul/8/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{subGroupCode}/{token}
  defaults:     {_controller: CatalogKiaBundle:Articul:getGroupBySubgroup, token: null}

catalog_kia_homepage:
    path:     /hello/{name}
    defaults: { _controller: CatalogKiaBundle:Default:index }
