catalog_saab_token:
  path:         /saab/catalog/0/{token}/{regionCode}
  defaults:     {_controller: CatalogSaabBundle:Catalog:regionsModels, token: null, regionCode: null}

catalog_saab:
  path:         /saab/{regionCode}
  defaults:     {_controller: CatalogSaabBundle:Catalog:regionsModels, regionCode: null}
  
catalog_saab_modifications:
  path:         /saab/catalog/1
  defaults:     {_controller: CatalogSaabBundle:Catalog:modifications}
  requirements: {_method: POST}

catalog_saab_complectations:
  path:         /saab/catalog/2/{regionCode}/{modelCode}/{modificationCode}
  defaults:     {_controller: CatalogSaabBundle:Catalog:complectations}

catalog_saab_groups:
  path:         /saab/catalog/3/{regionCode}/{modelCode}/{modificationCode}/{token}
  defaults:     {_controller: CatalogSaabBundle:Catalog:groups, token: null}

catalog_saab_subgroups:
  path:         /saab/catalog/4/{regionCode}/{modelCode}/{modificationCode}/{groupCode}/{token}
  defaults:     {_controller: CatalogSaabBundle:Catalog:subgroups, token: null}

catalog_saab_schemas:
  path:         /saab/catalog/5/{regionCode}/{modelCode}/{modificationCode}/{groupCode}/{subGroupCode}/{token}
  defaults:     {_controller: CatalogSaabBundle:Catalog:schemas, token: null}

catalog_saab_schema:
  path:         /saab/catalog/6/{regionCode}/{modelCode}/{modificationCode}/{groupCode}/{subGroupCode}/{schemaCode}/{token}
  defaults:     {_controller: CatalogSaabBundle:Catalog:schema, token: null}

catalog_saab_articuls:
  path:         /saab/catalog/7
  defaults:     {_controller: CatalogSaabBundle:Catalog:articuls}
  requirements: {_method: POST}

catalog_saab_group:
  path:         /saab/catalog/8/{regionCode}/{modelCode}/{modificationCode}/{subGroupCode}/{token}
  defaults:     {_controller: CatalogSaabBundle:Catalog:getGroupBySubgroup, token: null}

#------------------------------------------------------------------------------

vin_saab:
  path:         /saab/vin/0/{token}
  defaults:     {_controller: CatalogSaabBundle:Vin:index, token: null}

vin_saab_result:
  path:         /saab/vin/1
  defaults:     {_controller: CatalogSaabBundle:Vin:result}
  requirements: {_method: POST}

vin_saab_groups:
  path:         /saab/vin/3/{regionCode}/{modelCode}/{modificationCode}/{token}
  defaults:     {_controller: CatalogSaabBundle:Vin:groups, token: null}

vin_saab_subgroups:
  path:         /saab/vin/4/{regionCode}/{modelCode}/{modificationCode}/{groupCode}/{token}
  defaults:     {_controller: CatalogSaabBundle:Vin:subgroups, token: null}

vin_saab_schemas:
  path:         /saab/vin/5/{regionCode}/{modelCode}/{modificationCode}/{groupCode}/{subGroupCode}/{token}
  defaults:     {_controller: CatalogSaabBundle:Vin:schemas, token: null}

vin_saab_schema:
  path:         /saab/vin/6/{regionCode}/{modelCode}/{modificationCode}/{groupCode}/{subGroupCode}/{schemaCode}/{token}
  defaults:     {_controller: CatalogSaabBundle:Vin:schema, token: null}

vin_saab_articuls:
  path:         /saab/vin/7
  defaults:     {_controller: CatalogSaabBundle:Vin:articuls}
  requirements: {_method: POST}

vin_saab_group:
  path:         /saab/vin/8/{regionCode}/{modelCode}/{modificationCode}/{subGroupCode}/{token}
  defaults:     {_controller: CatalogSaabBundle:Vin:getGroupBySubgroup, token: null}

#---------------------------------------------------------------------------------------------

articul_saab:
  path:         /saab/articul/0/{token}
  defaults:     {_controller: CatalogSaabBundle:Articul:index, token: null}

articul_saab_find_token:
  path:         /saab/articul/1/{token}/{regionCode}
  defaults:     {_controller: CatalogSaabBundle:Articul:findByArticul, token: null, regionCode: null}

articul_saab_find:
  path:         /saab/articul/2/{regionCode}
  defaults:     {_controller: CatalogSaabBundle:Articul:findByArticul, regionCode: null}

articul_saab_modifications:
  path:         /saab/articul/3
  defaults:     {_controller: CatalogSaabBundle:Articul:modifications}
  requirements: {_method: POST}

articul_saab_complectations:
  path:         /saab/articul/4/{regionCode}/{modelCode}/{modificationCode}/{articul}/{token}
  defaults:     {_controller: CatalogSaabBundle:Articul:saabArticulComplectations, token: null}

articul_saab_groups:
  path:         /saab/articul/5/{regionCode}/{modelCode}/{modificationCode}/{articul}/{token}
  defaults:     {_controller: CatalogSaabBundle:Articul:saabArticulgroups, token: null}

articul_saab_subgroups:
  path:         /saab/articul/6/{regionCode}/{modelCode}/{modificationCode}/{groupCode}/{articul}/{token}
  defaults:     {_controller: CatalogSaabBundle:Articul:saabArticulSubgroups, token: null}

articul_saab_schemas:
  path:         /saab/articul/7/{regionCode}/{modelCode}/{modificationCode}/{groupCode}/{subGroupCode}/{articul}/{token}
  defaults:     {_controller: CatalogSaabBundle:Articul:saabArticulSchemas, token: null}

articul_saab_schema:
  path:         /saab/articul/8/{regionCode}/{modelCode}/{modificationCode}/{groupCode}/{subGroupCode}/{schemaCode}/{articul}/{token}
  defaults:     {_controller: CatalogSaabBundle:Articul:saabArticulSchema, token: null}

articul_saab_articuls:
  path:         /saab/articul/9
  defaults:     {_controller: CatalogSaabBundle:Articul:articuls}
  requirements: {_method: POST}

articul_saab_group:
  path:         /saab/articul/8/{regionCode}/{modelCode}/{modificationCode}/{complectationCode}/{subGroupCode}/{token}
  defaults:     {_controller: CatalogSaabBundle:Articul:getGroupBySubgroup, token: null}
catalog_saab_homepage:
    path:     /hello/{name}
    defaults: { _controller: CatalogSaabBundle:Default:index }
